### ISSUE TITLE
Can't work with Google API creditial files

### ISSUE THREAD

**Issue by jorisrobijn** [porjo/youtubeuploader#1]
Hi Ian,

I followed your instructions on creating a secrets file. I noticed you mention at one place setting it to "web" and elsewhere to "installed" application type. I tried both, but I cannot get it going. Actually I let the secrets file initially be generated by the Google API web manager, on the Credentials page. It is accepted, however, when I run your program a browser opens that wants to go to "http://localhost:4001/" which doesn't work (no response from server). I dont understand where this comes from, can't find that port in config file. This is the case for both installed and web types. I did set the redirect_uris to http://localhost:8080/oauth2callback .

Any idea why this goes wrong?

Thanks,
Joris

**Comment by jorisrobijn** [comment]
Fixed in my branch for which I've sent a pull request.

**Comment by porjo** [comment]
Thanks. Next time, put 'closes #1' or 'fixes #1' in your pull request, and that will auto-close the corresponding issue 😄

**Comment by jorisrobijn** [comment]
Oh thanks. First time working with github.com :)
