### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by RyanNutt** [porjo/youtubeuploader#10]
Hi - 
There've been several videos that I've tried to upload via URL that's stopped with an "unexpected EOC" message. When this happens it shows as processing in YouTube. 

Totally understand that stuff happens. What's weird is that they've all stopped at exactly 16,777,216 bytes transferred. Is there something special about that number as to why it fails at that spot. Each that's failed is at that same number.

Plenty of other videos have worked fine, and on a couple I've tried to upload again and it worked fine. 

ETA:
I went back and tried the one that just triggered the error and it uploaded without a problem, so I don't think it's specific to the file.

**Comment by porjo** [comment]
I've never seen that error before! A Google search is bringing up stuff relating to openssl...which is weird as Go doesn't use openssl. My guess is it's being generated by the Youtube API. Is the full error `Error making YouTube API call: unexpected EOC` ?

**Comment by RyanNutt** [comment]
Progress:     0.00 KiB/s, 16777216 / 73620292 (22.789%) ETA 16m39.84s2017/03/14     
17:05:10 Error making YouTube API call: unexpected EOF

Also got this a couple videos later. Not sure if it's related. Although it's weird that it went over 100%.

Progress:   648.12 KiB/s, 110113648 / 105388472 (104.484%) ETA       0s2017/03/14 17:19:24 Error making YouTube API call: googleapi: Error 503: Backend Error, backendError

**Comment by porjo** [comment]
Ah, `unexpected EOF` is a common error - I get that frequently. Unfortunately, the Go library for Youtube doesn't handle automatically resuming uploads very well...so it tends to fail completely. There is an open ticket about this [here](google-api-go-client#17)

Going over 100% is very odd...I'll have a play with it to see if I can reproduce.

**Comment by RyanNutt** [comment]
Understand that stuff happens and I assumed it wasn't something specific to your code. It's just weird that it's always been at the exact same point on several different files. I've seen probably half a dozen of the EOC messages and they've all been at the same point. 

Either way, I just re run the upload and it works fine the second time around.

**Comment by porjo** [comment]
I've not had any EOF errors on my own uploads for quite some time. I'm putting that down to improved stability of Youtube's upload servers and/or improvements in the Youtube API library. Closing this ticket.
