### ISSUE TITLE
madeForKids field doesn't work

### ISSUE THREAD

**Issue by Zennii** [porjo/youtubeuploader#103]
I've tried to use the madeForKids metaJSON field to set the default for my uploads (false), however uploaded videos simply have the setting remain unset which youtube by default considers to be "Yes, it's made for kids". That is, unless youtube is acknowledging this setting but not displaying it on the UI. I have not tried setting it to true.

![image](https://user-images.githubusercontent.com/18521883/131229088-ae2f6465-a2e8-4e4c-9d3e-9c0fca98c577.png)

**Comment by Zennii** [comment]
From what I've found, the field you're using may be read-only. There's a different field selfDeclaredMadeForKids that has to be used: https://developers.google.com/youtube/v3/live/docs/liveBroadcasts#status.selfDeclaredMadeForKids

**Comment by Zennii** [comment]
In the livestreaming API madeForKids is readonly (Which it seems like they forgot to note) so I'm wondering if maybe the madeForKids field in the uploading API is the same. There is another field selfDeclaredMadeForKids https://developers.google.com/youtube/v3/docs/videos#status.selfDeclaredMadeForKids

**Comment by porjo** [comment]
Thanks for the report - it was in fact `selfDeclaredMadeForKids` that needed setting. Fixed in latest release.
