### ISSUE TITLE
Error 400: Media type 'text/plain; charset=utf-8' is not supported. , badRequest

### ISSUE THREAD

**Issue by mouchyntamu** [porjo/youtubeuploader#104]
When I try to use this utility, I get the following error message:

Error making YouTube API call: googleapi: Error 400: Media type 'text/plain; charset=utf-8' is not supported. , badRequest

It was working great for automated daily uploads until May 1, 2021. Did something change with the youtube api around that time? Any idea what could be causing this error 400?

Here's the command I'm using:

`./youtubeuploader_linux_amd64 -secrets client_secrets.json -filename 2021-05-01-se.mp4 -title '2021-05-01-se' -headlessAuth -metaJSON 2021-05-01-se.json`

Thanks,
Chris

**Comment by imcuneo** [comment]
Different timing, 2021/10/26, but same error message for me.

My command:
`./youtubeuploader_linux_armv7 -privacy unlisted -filename /var/www/html/media/tl_0087_2021-10-17.mp4`

I get:
`Error making YouTube API call: googleapi: Error 400: Media type 'text/plain; charset=utf-8' is not supported. , badRequest`

**Comment by imcuneo** [comment]
Well, I few minutes in and I think I have the solution.

My SD card had filled while FFMpeg was making said MP4, and so it was unfinished, and Youtube rejected it for a lack of correct header.

**Comment by porjo** [comment]
@mouchyntamu can you check your source file to see if they are valid video files?

**Comment by mouchyntamu** [comment]
@porjo Argh! That's exactly the problem. I'm using this tool to batch upload 50ish videos per day to youtube and it was hung up on a zero-length video file that was not generated correctly. Sorry about that!

Cheers

**Comment by porjo** [comment]
fyi, I've added a check which will output a warning message to console if the input file doesn't look like a video.
