### ISSUE TITLE
location in JSON doesn't work

### ISSUE THREAD

**Issue by threehappypenguins** [porjo/youtubeuploader#106]
In my JSON, I have the latitude and longitude, as well as locationDescription (because the location building has a name), and in the YouTube video I upload, it's blank. So I have to manually add it in the video settings in Yt.

**Comment by porjo** [comment]
Unfortunately, that functionality was removed from the API by Google. No explanation given. See: https://developers.google.com/youtube/v3/revision_history#release_notes_06_01_2017

I've pushed an update to remove reference to this in the README
