### ISSUE TITLE
Install this in Linus VPS

### ISSUE THREAD

**Issue by cxt532** [porjo/youtubeuploader#107]
Hi,

In the user guideline, I have done the 'setup' step and downloaded the client secrets JSON file 

But there's not much instructions in the 'download' step, and I have difficulties installing this in my Linus VPS, can you provide some detail command lines

Thank you,

**Comment by cxt532** [comment]
Hi,

I have downloaded the matched precompiled binary and unpacked it

I got a file called youtubeuploader_linux_amd64

What command line should I use to execute this file though ?

**Comment by porjo** [comment]
You can run it like this:
```
./youtubeuploader_linux_amd64
```

**Comment by cxt532** [comment]
Thank you! will test it further
