### ISSUE TITLE
Progress status

### ISSUE THREAD

**Issue by Toniob** [porjo/youtubeuploader#109]
Hi,

It should be great if we could have the status of the upload, what was sent and what remains. Maybe an option --progress which gives it in real time, and/or, like dd or other tools, you send an USR1 signal, and it prints the current status.

Do you think it is possible ?

Thanks a lot for your app which helps me a lot with my videos

**Comment by porjo** [comment]
I'm glad to hear you find it useful.

A progress status is already displayed by default, with option to suppress it with `-quiet` parameter. What output do you see when you do an upload?

**Comment by Toniob** [comment]
Ok, I am that dumb ! But I do remember now. I’m using your app in a script. The script check if there are .mp4 or .mkv in a directory. If so, it starts uploading those videos on youtube. If the upload is successful, the file is deleted, and the loop continues. I’m starting this script automatically with a .path system unit. So when I put a file in the directory, the script is called without my intervention.

That’s why I’ve put the -quiet flag. Because if I don’t, the progress is logged in the systemd service log, and that’s quite much. But now, I can’t know the progression of the upload. So, my need is quite specific, but do you think we could have other behaviors ? I’m thinking of the signal one (the current progress is printed when a signal is sent to the app), or maybe, only printing the progress every 5 or 10% of completion ?

What do you think ? Thanks again a lot for you work.

**Comment by porjo** [comment]
I've pushed new release 21.07 which supports sending signal `USR1` to the process e.g. `kill -USR1 <pid>`
