### ISSUE TITLE
No issue, just a success story

### ISSUE THREAD

**Issue by besweeet** [porjo/youtubeuploader#11]
With little-to-no programming knowledge, I was able to get this going in under two minutes. I gave it a test MP4 (setting the privacy to unlisted) with a basic title and description. Uploaded with no issues at all.

I guess my only suggestion is to have a way to insert line breaks within the description (or maybe there is already?).

**Comment by porjo** [comment]
I'm glad to hear it's working for. You can use `\n` in the meta json file as described in the README here: https://github.com/porjo/youtubeuploader#metadata

**Comment by besweeet** [comment]
> Use `\n` in the description to insert newlines.

Ah, the only part of the readme I didn't read -- thanks :D.

**Comment by besweeet** [comment]
@porjo Is it possible to incorporate logging capabilities? I'm planning on using this as a scheduled task within Windows and I don't believe it logs the actual command. Though I think I can do that with a batch script.

**Comment by porjo** [comment]
Sorry, I don't understand. You have the command already - can't you just echo that somewhere? The output from youtubeuploader can be redirected by appending  `> logfile.txt 2>&1`
