### ISSUE TITLE
Token has been expired or revoked

### ISSUE THREAD

**Issue by hildebrau** [porjo/youtubeuploader#115]
So, I had this working for a week or so.  Now it's saying 
Response: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}

I saw a closed issue that referenced the Oauth consent screen needed to be in production status, not testing, or it only lasts a week.  That sounded like the issue; so, I set it to production.   I still hit the same error, however.

So, I went back to GCP Credentials and "reset secret" for the youtubeuploader "web application" that I had created.  I downloaded the new JSON and updated the client_secrets.json file.

No change.

I saw another closed issue that said to remove that file.  I tried that and ran the uploader with and without -headlessAuth and it didn't seem to "do anything".. just complained that it needed that file.  So, I put it back.

I know the very first time I ran this, it did show the URL to copy and paste into a browser and I authenticated it.  I'm just not sure how to make that happen again.

I'm afraid to kill my web application and start over, as I had to jump through some hoops to get Youtube to trust my API and allow my videos to not be locked in restricted mode.  I really don't want to have to do that again, as I quite honestly don't remember how I pulled off that stunt.  Hah!

Any tips to guide me in the right direction would be greatly appreciated!

Sample full output:

% youtubeuploader -headlessAuth -filename 2022-04-24.mp4
Uploading file '2022-04-24.mp4'

2022/04/27 17:26:30 Error making YouTube API call: Post "https://youtube.googleapis.com/upload/youtube/v3/videos?alt=json&notifySubscribers=true&part=snippet&part=status&part=recordingDetails&prettyPrint=false&uploadType=resumable": oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}

**Comment by hildebrau** [comment]
I think I answered my own question.  There was a request.token file in the directory that needed to be removed first. Then I ran the -headlessAuth option and authorized it via a manual link and I'm back in business.

request.token file had an expiration, I guess.  I see a "refresh_token" in there.  Will this app ever use that to refresh the token?  Hopefully w/ the consent screen flagged as production, it won't expire after a week.  We shall see.

**Comment by porjo** [comment]
Yes, the oauth2 library will handle token refresh automatically. So if you're seeing that error, it means you either didn't have a refresh token, or some config on your account/app is preventing the refresh behaviour. For example, your app may be in 'testing' mode (see [here](https://stackoverflow.com/a/67966982/202311)) which causes token to expire after 7 days.

**Comment by hildebrau** [comment]
Thanks.  I guess I'll find out late next week if it expires or not.  I did change something from test to production this week. It was under a link named consent something or other.

**Comment by porjo** [comment]
Sorry to repeat the bit about testing status - didn't read your first comment properly!

**Comment by oliverw** [comment]
So if my token expires despite seeing a refresh token in the json content, it is because my application is in _test_ mode?

**Comment by hildebrau** [comment]
That is likely, yes.  I don't recall what I did to get out of test mode; but I do know that my token hasn't expired since my comments above!
