### ISSUE TITLE
Unable to perform headlessAuth

### ISSUE THREAD

**Issue by ocean2000pl** [porjo/youtubeuploader#116]
There seem to be a problem with headless authorisation. Google returns Error 400: invalid_request

The problem, with a hint for possible solution is discused here:
https://stackoverflow.com/questions/71318804/google-oauth-2-0-failing-with-error-400-invalid-request-for-some-client-id-but

**Comment by porjo** [comment]
Thanks for the report. I think this sums it up (taken from linked [Google developer doc](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob))

> OAuth [out-of-band](https://developers.google.com/identity/protocols/oauth2/native-app#manual-copypaste) (OOB) is a legacy flow developed to support native clients which do not have a redirect URI like web apps to accept the credentials after a user approves an OAuth consent request. The OOB flow poses a remote phishing risk and clients must migrate to an alternative method to protect against this vulnerability. New clients will be unable to use this flow starting on Feb 28, 2022.

Google want to stop apps doing headlessAuth (where the auth code is copy and pasted into the command prompt) as it is less secure.

Unless anyone can suggest another solution, you will need to generate the token file locally first (somewhere with a web browser), then copy the resulting token file along with youtubeuploader and client_secrets.json to the remote host.

**Comment by ocean2000pl** [comment]
Does it really work? (auth steps at the top of the README) 

I've got access_denied, error 403, when I tried to generate token. 

"The developer hasn’t given you access to this app. It’s currently being tested and it hasn’t been verified by Google. If you think you should have access, contact the developer"

**Comment by porjo** [comment]
@ocean2000pl thanks for raising it.

I've updated the README with an extra step - you need to also add a 'test user' in the OAuth setup.

**Comment by porjo** [comment]
fyi, I have removed the `-headlessAuth` parameter in latest release 22.03.

**Comment by p0i5k** [comment]
I don't understand why `-headlessAuth` parameter was removed. I'm still using the evertonstz fork of tokland/youtube-upload. Headless authorization still works.

**Comment by porjo** [comment]
It was removed because an issue was reported with it which, at the time, seemed to be caused by Google deprecating it.

> Headless authorization still works.

Just a guess (I'm not familiar with how youtube-upload does it) but it could be that Google are still allowing it for clients created before the change (I don't mean the utility, I mean the oauth2 client created in Google Developer Console).

I'm not opposed to adding it back if someone wants to test it and send a PR.
