### ISSUE TITLE
Does the program have its own API?

### ISSUE THREAD

**Issue by faqu1** [porjo/youtubeuploader#117]
Do I need my google api to use this program? Or does the program have its own api, is it enough for me to register for an account through oauth2?

**Comment by porjo** [comment]
This utility uses Youtube's API. Youtube is owned by Google, and uses Google oauth2 backend. You need to create a Google developer account to use oauth2 - see instructions in the [README](https://github.com/porjo/youtubeuploader/blob/master/README.md#youtube-api). Does that answer your question?

**Comment by faqu1** [comment]
But there you need to go through verification from Google, right?
