### ISSUE TITLE
Activate monetization

### ISSUE THREAD

**Issue by umrug** [porjo/youtubeuploader#12]
Hi,
  is there a way to pass an argument to activate monetization for uploaded video?
Thanks,
Francesco

**Comment by porjo** [comment]
No this isn't supported in the general Youtube API. From what I understand this feature is only available to 'YouTube content partners' i.e. it's a special level of access you have to apply for - see [here](https://developers.google.com/youtube/partner/)

**Comment by umrug** [comment]
Yes, sure. I'm already YouTube partner.
But when I upload video by youtubeuploader they have monetization off (even if it is on by default and is active automatically after default YouTube uploading process) and I have to switch on manually later.
No chance to see it implemented by API?
Thanks,
Francesco 


Il giorno 5 Apr 2017 14:13, alle ore 14:13, Ian Bishop <notifications@github.com> ha scritto:

**Comment by porjo** [comment]
I've created a [new branch](https://github.com/porjo/youtubeuploader/tree/monetization) which might work for you. You'll have to compile the Go code yourself.
Include this in the meta json:
```json
{
  "monetization": {"allowed": true}
}
```
I'm not able to test this myself as I'm not a Youtube partner. When I try to use it I get error: `Error 400: {0}, unexpectedPart`

**Comment by jorisrobijn** [comment]
Would it be possible to get this into the main branche?

**Comment by porjo** [comment]
I've just updated the monetization branch to bring it up-to-date with the main branch. Once someone has confirmed that the change made there works as required, then I will merge it into the main branch.

**Comment by jorisrobijn** [comment]
Hi, I finally tried this, but it gives me the following error (probably the same as you had).
I do have the youtube CMS.

`2019/06/23 15:44:57 Error making YouTube API call: googleapi: Error 400: {0}, unexpectedPart`

**Comment by porjo** [comment]
I've looked at this again, and it appears there is more involved - see:
- https://stackoverflow.com/questions/18800665/how-to-enable-monetization-for-videos-uploaded-with-youtube-data-api-v3
- https://developers.google.com/youtube/partner/upload_claim_sample
(Thanks to @bantini for the [links](https://github.com/googleapis/google-api-nodejs-client/issues/833#issuecomment-341788762))

If anyone wants to have a go implementing that, I'd happily consider a PR

**Comment by Scoffins** [comment]
This would be a very welcome addition to the main branch. How does one go about "compiling" the code in the Monetization branch? Probably a very basic thing to do when you know how, but I've never done it before, my experience lies in web development. Thanks.

**Comment by porjo** [comment]
@Scoffins actually I think the monetization branch is no longer relevant as it doesn't implement what's described in my previous comment. Whoever implements this should be creating a new branch off master and implementing the changes there. As for compiling the code, it's not really anything specific to this project - just standard Go compilation steps (which you can read about in [Go doco](https://golang.org/doc/install)). For example, on my system (Fedora Linux) the following steps are all that's needed:

- `dnf install golang`
- `go get github.com/porjo/youtubeuploader`

This will create directory `go` under your home directory (if it doesn't already exist), and inside there these files:
```
go/bin/youtubeuploader  <--- compiled binary
go/src/github.com/porjo/youtubeuploader/ <--- source code
```

**Comment by porjo** [comment]
I'll close this now, and reopen if/when the API gets updated.
