### ISSUE TITLE
Upload Speed

### ISSUE THREAD

**Issue by lschaef** [porjo/youtubeuploader#121]
I got this working, but when I used it to upload a 1.7GB file the progress bar said it was uploading at about 3Mbps and it would take over an hour.  I stopped that and uploaded the same file manually through the website and it finished in just a few minutes.

Am I missing something in the configuration or does YouTube throttle connections coming through the API?

**Comment by porjo** [comment]
That's strange. It's possible there is some kind of throttling going on, but seems unlikely that it would be applied based on usage of API alone. It may be that the website uploads file chunks in parallel, but I wouldn't expect such a large difference in speed. Another possibility is the endpoint used for upload via API has higher latency, packet loss.. It would be interesting to see if your slow result is consistent over time.

**Comment by lschaef** [comment]
I ended up doing a bunch of Windows/Network tweaks on the computer and it appears one of them solved the issue.  Something was slowing down my upload speed from the command prompt even though my upload speeds to YouTube and speed tests in the browser were all fine.
