### ISSUE TITLE
2022/06/24 09:46:21 Error making YouTube API call: googleapi: Error 403: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>., quotaExceeded

### ISSUE THREAD

**Issue by InvalidAccount69** [porjo/youtubeuploader#123]
i try upload video but give me this error: 2022/06/24 09:46:21 Error making YouTube API call: googleapi: Error 403: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>., quotaExceeded
any idea for fix it?

**Comment by porjo** [comment]
See #119
