### ISSUE TITLE
Upload Stuck at 0.000%

### ISSUE THREAD

**Issue by tanmaywadhwa** [porjo/youtubeuploader#124]
Hey All,

Tried the setup and began uploading a file but the progress stays stuck at 0.000%. I see the video as pending in the web UI, so I know the upload is initiating.
Is there any way for me to look at the video upload logs to see what error the API might be throwing?

**Comment by Fijxu** [comment]
You cloud use `proxychains` and `mitmproxy` to intercept the traffic and see the HTTP traffic :p (Linux)

**Comment by porjo** [comment]
Is this still a problem? If so, please copy and paste the command line and any output.

**Comment by tanmaywadhwa** [comment]
I eventually figured out that it was a problem with the upload size. My
youtube account needed to be verified to allow for uploads larger than a
certain size.

It was more of a hit and trial approach through. I wish youtubeuploader
published some logs so I could figure out from the api response as to what
the problem was.

**Comment by porjo** [comment]
If Youtube API returns an error, youtubeuploader should output that error to the console and quit. It seems strange that this is related to file size. Youtube won't know the size of your file at the beginning, and so you would expect the upload to progress to a certain point before Youtube decides that it is too large.

I don't have time at the moment to add increased logging, however it should be easy enough to do if you're familiar with Go. Do you want to have a try yourself?
