### ISSUE TITLE
Select channel

### ISSUE THREAD

**Issue by jorisrobijn** [porjo/youtubeuploader#13]
I can't find a way to select what channel the video goes to. It doesn't go to the channel selected as default channel for the account, but just to the account's own channel...

**Comment by porjo** [comment]
Hi, I've just uploaded a [new version](https://github.com/porjo/youtubeuploader/releases/tag/1.6.2) which allows you to specify the channel ID in the [`meta.json` file](https://github.com/porjo/youtubeuploader#metadata)

**Comment by jorisrobijn** [comment]
Thanks for your quick respons. However, I still don't get it to upload to the correct channel. I've verified that the json file is used but editing it with some charachters of nonsense, and it complains then. (however it does continue, which I would consider dangerous, but that's another matter). Have you tried it with a real channel?

**Comment by porjo** [comment]
my apologies, I didn't test! I've tested now and the video always goes to the base account's channel, not the additional channel I've created. I've confirmed that it is definitely sending the correct channel id in the request, so I guess the API is ignoring that. However, not completely ignoring it - as you found, if I put in random characters for the channel ID it causes an error. For me it stops the upload with this message `googleapi: Error 503: Backend Error, backendError`.

The [API documentation](https://godoc.org/google.golang.org/api/youtube/v3#VideosInsertCall.OnBehalfOfContentOwnerChannel) talks about the authorising account needing to be a 'content partner' and linked with a 'CMS account' . I'm afraid this one is beyond my experience. Hopefully someone else will have some insights.

**Comment by Cinerar** [comment]
You should rerequest authorization and select another channel when authorizing.

**Comment by porjo** [comment]
@Cinerar thanks, if you could check your code that would be helpful. Everything I'm reading points to having 'content partner' status as a pre-requisite. I have no interest in becoming a partner, so wouldn't be able to test any potential solution. Someone else will need to develop this feature.

**Comment by jorisrobijn** [comment]
I am logged in as content partner. I will clear the credits and try to select the correct channel again.

**Comment by jorisrobijn** [comment]
It appears I didn't select the correct account when authorizing, because it now _does_ appear on the indicated channel. So I will close this issue!

**Comment by porjo** [comment]
@jorisrobijn that's good to hear. Have you confirmed that your are able to upload to a channel that is not set as the default channel?

**Comment by jorisrobijn** [comment]
Actually I have not. But if channel is not set, it goes to the accounts main channel (not default channel). The hardware is packed again, I can check later.
