### ISSUE TITLE
-notify or meta.json notifySubscriber is always True

### ISSUE THREAD

**Issue by Nexxxy** [porjo/youtubeuploader#130]
Hi, 

dont know wether its a bug of youtube api or of youtubeuploader. 
When i try to use

youtubeuploader ... some params ... -notify false

it still is activated on youtube :
![image](https://user-images.githubusercontent.com/6639192/193461074-ee90e037-78ec-4c65-9918-88ec9b20ba86.png)

(Sorry for beeing everything german .. there is no fast way to switch languages)

2nd part:

if you reorder the parameters (notify false before secrets parameter) like this :
`.\youtubeuploader.exe -filename .\testfile.mp4 -cache "D:\projekte\python-workspace\uploadwrapper\uploadkeys\request.token" -title "test 123" -notify false -secrets "D:\projekte\python-workspace\uploadwrapper\client_secret_webapp-raspy-nyu.json"`

the result is that it is no more able to find the secrets file ..
instead it searches in the current directory and the default file <client_secrets.json>

> 2022/10/02 17:08:17 Error building OAuth client: Cannot read configuration file:
> Please configure OAuth 2.0
> 
> To make this sample run, you need to populate the client_secrets.json file
> found at:
> 
>    D:\projekte\python-workspace\nyu\NexYoutubeUploader\bins\client_secrets.json
> 
> with information from the {{ Google Cloud Console }}
> {{ https://cloud.google.com/console }}

can recreate this bug in linux and windows

BR
Nexxy

**Comment by porjo** [comment]
Both issues are due to a quirk with the way Go handles boolean parameters. Boolean must either have no argument (implicit true), or be followed by equal sign and argument value (e.g. `-notify=false`)

The second issue is due to the flag parsing hitting `false` and deciding that it marks the end of the flags (as it is an unrecognised flag). Any flags following that are ignored.

I've pushed an update to README to clarify that.

**Comment by Nexxxy** [comment]
Ty buddy. Keep up the good work.

A nice-to-have-feature for me (didnt find it in the readme tho) would be to set the privacy (unlisted / private / public) 
to new created playlists like [youtube-upload from tokland](https://github.com/tokland/youtube-upload) did it.

(Any way to gift you guys a beer or coffee ?)
BR 
Nexxy

**Comment by porjo** [comment]
> A nice-to-have-feature for me (didnt find it in the readme tho) would be to set the privacy (unlisted / private / public)
to new created playlists like [youtube-upload from tokland](https://github.com/tokland/youtube-upload) did it.

The way it should work is if a playlist gets created, the new playlist will have its privacy status set to the same as the video privacy status. I can't test that at the moment - if you can test and let me know, it would be appreciated.

> Any way to gift you guys a beer or coffee ?

Haha, not at the moment - maybe I'll add a link to the project.
