### ISSUE TITLE
Feature request: Playlist creation w/o upload

### ISSUE THREAD

**Issue by johndmulhausen** [porjo/youtubeuploader#131]
I had modded tokland's script so that it had a mode where I could just create a playlist, without requiring an upload. That way I could grab the metadata and put a link to the playlist that matches the video right in the description and get people to see things in the right sequence. Super awesome. Could a feature like this be added to `youtubeuploader`? Maybe just a `--playlist` flag that accepts a title would be good, then it makes `--filename` optional?

**Comment by porjo** [comment]
I'm hesitant to modify the utility like that as it distracts from the core focus of uploading videos. This utility isn't intended to be a general purpose Youtube channel management utility. I'd be more in favour of having a standalone utility that simply creates playlists.

**Comment by johndmulhausen** [comment]
I understand what you're saying. Do you see what I'm saying though about the importance of being able to link to the playlist that a video belongs to right from the description? Is there some method of doing that you would recommend with the functionality present now? My feeling is playlists are such a fundamental part of uploading videos that they are part of the core focus -- which is why the ability to specify them is present in the upload capability to begin with. Also I don't think the utility veers into "general purpose channel management" just because you can organize the videos into playlists and add description links. On the contrary things like that make video uploads enabled by the utility far more powerful for the creators and useful for the viewers.

**Comment by porjo** [comment]
I do understand what you're saying, but still feel the same way. I'm going to close this now. If other people express interest, then I'll reconsider.
