### ISSUE TITLE
Processing abandoned

### ISSUE THREAD

**Issue by ChristianErdtmann** [porjo/youtubeuploader#133]
Hey can you explain why i get for 2 of my channels in 50% of the tries to upload the Video an error in my youtube studio:
Processing abandoned
The video could not be processed

For 2 of 4 Channels it work good but the other channels often got problems with the upload and i dont know why.
If i start the upload with the tool manually, the error never appears, but i got a sheduled task automation on a windows server wich start the upload over a batch script, that works fine for 2 of 4 Channels but the most time its not working. Any idea how to solve this or why it happens?

**Comment by porjo** [comment]
Try adding the `-debug` flag and capture the output for the scheduled task to see what it's doing.

**Comment by ChristianErdtmann** [comment]
Hey ich bin noch nicht dazu gekommen, meine software so umzuschreiben, dass es im debug mode aufgerufen wird, aber mir ist nun folgender error aufgefallen:

WARNING: input file doesn't appear to be a video. It has content type 'image/jpeg'
2022/11/05 07:25:49 Error building OAuth client: listen tcp :8080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
exit status 1

Wie kann ich das vermeiden?

**Comment by ChristianErdtmann** [comment]
hey i had no time to rewrite my software to debug mode but i will do this in the next days and give you feedback.
