### ISSUE TITLE
Running on a Pi zero

### ISSUE THREAD

**Issue by AhTeeGuu3u** [porjo/youtubeuploader#135]
First of all, thank you very much for publishing this app.

1. The app runs ok on a very low powered pi zero, at the start the cpu load is quite high for  some time, later we land at an average load of 0.9 with an upload speed of 10Mbit/s.
2. I had to compile it for myself (first time for go), and It also pulled in some X resources, and I am on a headless server... Could you also provide an armv6l binary?
3. The progress indication does not update, it is stuck on
Progress:     0.00 Kbps, 184 / 29913418488 (0.000%) ETA -2h52m23.46s
for hours, ETA seems to be working. The upload works fine.

Thx anyway and cheers,
dennis

**Comment by porjo** [comment]
I'm glad to hear you've found it useful. I've [added](https://github.com/porjo/youtubeuploader/commit/c960f3bcca50a094adc9cc208fabc813c2b80e8d) armv6 support now. I'll track the progress bar issue in #136

**Comment by porjo** [comment]
Progress bar bugs should be fixed in latest release [22.05](https://github.com/porjo/youtubeuploader/releases/tag/22.05). @AhTeeGuu3u can you confirm?

**Comment by AhTeeGuu3u** [comment]
Thanks! Binary works out-of-the box.
Progess looks good:
Progress:    10.37 Mbps, 279773184 / 771718859 (36.3%) ETA    6m19s
