### ISSUE TITLE
Progress bar random numbers

### ISSUE THREAD

**Issue by pquerner** [porjo/youtubeuploader#136]
Uploading a video produces a progress bar like this on my system since updating from ubuntu 12.04 to 16 (and to 18 and to 20).04 for a while now.
(But also on a complete fresh install of Ubuntu 22.04)

While the upload still works, its not pretty to look at.

```
Progress:     0.00 Kbps, 186 / 7309368936 (0.000%) ETA 2562047h39m15.12s
```

Any idea what could cause something like this?

My OS:
Ubuntu 20.04.5 LTS

**Comment by porjo** [comment]
Yeah, there's been reports of similar weird behaviour for progress bar. My hunch is a bug in the [flowrate](https://github.com/porjo/go-flowrate) library I'm using. I've been meaning to swap that out for something else, but haven't got around to it. I'll keep this issue open to track that.

**Comment by porjo** [comment]
Progress bar should be fixed in latest release [22.05](https://github.com/porjo/youtubeuploader/releases/tag/22.05). @pquerner can you confirm?

**Comment by pquerner** [comment]
22.06 looks like this now:

`Progress:    46.11 Mbps, 347160764 / 14909830868 (2.3%) ETA    42m6s`

Maybe we can don't show bytes?

**Comment by porjo** [comment]
Thanks for the confirmation. I'd like to leave the output format as-is for now.
