### ISSUE TITLE
support for playlists?

### ISSUE THREAD

**Issue by a7madgamal** [porjo/youtubeuploader#14]
does this script support playlists?
hopefully multiple playlists

**Comment by porjo** [comment]
No, but should be possible to add

**Comment by elpresti** [comment]
Hello Porjo! great work with your youtubeuploader ! It would be great to support adding uploaded videos to a playlists, that's the only reason I need to choose tokland/youtube-upload

**Comment by porjo** [comment]
I've just pushed a new release which supports playlists. Some things to note:

- add `playlistId` to your JSON metadata file
- modifying a playlist requires extra permissions, so you must request a new token (just delete `request.token` file before running `youtubeuploader`)
- only supports a single playlist, but multiple playlists should be possible in future

**Comment by elpresti** [comment]
Amazing! I'll check it and migrate to your youtubeuploader!
Thanks!

**Comment by porjo** [comment]
Turns out the extra permissions weren't necessary after all, so no new token required! I've pushed another release

**Comment by DaniDipp** [comment]
Is there a reason this is only supported in the json file and not as cli flag, or just an oversight?

**Comment by porjo** [comment]
@DaniDipp I've tended to only add essential things as new cli flags. I'd be happy for all options to have a cli flag, I'm just not interested in implementing it myself. If it were to happen, I'd want to use a better display format for cli flags i.e. grouping similar flags together
