### ISSUE TITLE
DailyMotionUploader.exe - Interested?

### ISSUE THREAD

**Issue by Scoffins** [porjo/youtubeuploader#141]
I couldn't find a way to inbox you so this will have to do :)

I wrote a BATCH script which uses curl.exe and jq.exe to upload videos to DailyMotion. I've used your YouTube Uploader for quite some time and wondered if you'd be interested in using my code to create an equivalent dailymotionuploader.exe ?

**Comment by porjo** [comment]
Thanks for your interest but I'm not interested in doing that work. Why not have a go yourself?

**Comment by Scoffins** [comment]
I don't have the skills to convert the code into an exe file. I also have no time/motivation to do so as cURL is working great for me. I only offered you my code because I thought it would make a great companion project to go with this one. Back when I was first learning to write BATCH files, your youtubeuploader project really saved me, as at the time I didn't know how to write cURL. Nobody else seems to be working on a dailymotion version (afaik), and having followed your work here for several years, you were the first person I thought to ask. My offer is always open should you change your mind :)
