### ISSUE TITLE
caption upload apparently successful but not applied to video

### ISSUE THREAD

**Issue by solace** [porjo/youtubeuploader#146]
Hello!

I'm running the uploader with this command, where the `metaJSON` contains a structure that looks like the one in the `README`.

```
./youtubeuploader -secrets client_secret_yt.json -notify=false -filename file.mp4 -caption caption.en_AU.srt -thumbnail thumbnail.jpg -metaJSON meta.json
```

The SRT is a timed file and the console returns `Caption uploaded!` but the video doesn't appear to be using the uploaded caption.

Does this option support SRTs?

Thanks!

**Comment by porjo** [comment]
@wolfram77 do you have any thoughts on this?

**Comment by porjo** [comment]
Thanks @wolfram77 for the confirmation. 

@solace can you provide more detail about how you are testing? 

FYI, youtube doco says this about `.srt` files here https://support.google.com/youtube/answer/2734698?hl=en#zippy=%2Cbasic-file-formats

> Only basic versions of these files are supported. No style info (markup) is recognized. The file must be in plain UTF-8.

**Comment by solace** [comment]
Hello! Thanks @porjo and @wolfram77 for being so quick with this.

@wolfram77 was right, it does work. I was using YouTube Studio -> Video details -> Subtitles to verify but as they said, it doesn't show up there, but is applied and is visible in regular playback. Can this please be added to docs?

Thank you. :)
