### ISSUE TITLE
Need to be able to specify channel destination under YT account

### ISSUE THREAD

**Issue by scissorfighter** [porjo/youtubeuploader#147]
This code works great so far!  Unfortunately, it seems to only be able to upload a video to a given user's default video channel.  Many users (myself included) manage multiple channels under the same YT account.  So there needs to be a way to define which channel the video gets uploaded to.  If I'm reading the YT Data API  v3 documentation right, I think this may be accomplished through the use of _onBehalfOfContentOwner_ and _onBehalfOfContentOwnerChannel_ parameters in the Videos:Insert method.  
https://developers.google.com/youtube/v3/docs/videos/insert?hl=en_US

Thanks!

**Comment by porjo** [comment]
This is a feature that I'd be happy to accept a PR for, but wouldn't spend time on myself. I note that the doco says `*Note:* This parameter is intended exclusively for YouTube content partners`. I'm not a content partner, so can't test this.

**Comment by porjo** [comment]
Closing for now

**Comment by Sarke** [comment]
#190
