### ISSUE TITLE
Allow metaJSON to take arbitrary values matching API expectations

### ISSUE THREAD

**Issue by patcon** [porjo/youtubeuploader#15]
Hi! This is a great tool, so thanks!

I see that the metaJSON file is interpreted manually, but perhaps they could be mapped more exclusively to YouTube API's expectations?

ie. https://developers.google.com/youtube/v3/docs/videos/insert#request-body

This would allow me to set recordingdate, but would also help others with niche requests :)

**Comment by porjo** [comment]
Thanks for the suggestion. I'd prefer to add specific features as required, rather than mapping large chunks of API by default. I've added 3 additional fields to the meta json file now e.g.

```json
 "recordingdate": "2017-05-21",
 "location": {
    "latitude": "2.2945",
    "longitude": "48.8584"
  },
  "locationDescription":  "Eiffel Tower"
```

See new version [1.6.3](https://github.com/porjo/youtubeuploader/releases/tag/1.6.3)

**Comment by patcon** [comment]
Thanks so much @porjo! I do appreciate the ridiculously fast responsiveness.
