### ISSUE TITLE
Actually `client_secrets.json` is stored in `root/.config/youtubeuploader`

### ISSUE THREAD

**Issue by iWECon** [porjo/youtubeuploader#158]
<img width="851" alt="CleanShot 2023-01-22 at 20 22 37" src="https://user-images.githubusercontent.com/16604027/213915573-409659a6-6c66-4c81-b000-8575c33f2ded.png">

it is not stored in same directory.

**Comment by iWECon** [comment]
Ubuntu 20.04

**Comment by porjo** [comment]
See this comment on https://github.com/porjo/youtubeuploader/issues/129#issuecomment-1286426670 for an explanation of default behaviour.
