### ISSUE TITLE
How do you set a video to "public"?

### ISSUE THREAD

**Issue by pgregg88** [porjo/youtubeuploader#160]
Thank you for your great work on this.

I've tried setting the video to public via -privacy public and with a json file. However, each time it is published as private. Is there a default setting on my YouTube account I need to set or something I'm missing? Thanks.

**Comment by porjo** [comment]
See #86

**Comment by pgregg88** [comment]
@porjo Apologies. I omitted some detail. I've going through the audit. My app is authorized to publish and they increased my daily upload limit. I can successfully publish my videos to my YouTube channel using youtubeuploader.

Everything works with the exception that my video stays in the state of Visibility = private. (not Private/Blocked).

After the upload completes, I'm able to change the visibility from Private to Public manually through the web UI, but I haven't been able to do it with youtubeuploader.

Should I be making a second call to change the visibility after the upload completes?

Thanks in advance.

The picture shows what the video looks like after publishing via YouTubeuploader.

Here's my json for this same video. (indents are correct in the actual json)
{
	"madeForKids": false,
	"embeddable": true,
	"license": "creativeCommon",
	"publicStatsViewable": true,
	"recordingdate": "2023-02-12",
	"title": "02/12/2023: Lake Travis, Texas (Austin, TX): 4K, 60fps Daily Weather & Boat Traffic Timelapse Video",
	"tags": ["laketravis", "austin", "weather", "wx", "timelapse"],
	"privacy": "public",
	"description": "4K, 60fps Daily Weather & Boat Traffic Timelapse Video taken near Lakeway, Texas (Austin, Texas)",
	"categoryId": "28",
	"playlistIds": ["PLFN-n1UuTGMFbSg3XSun34o3expxXXXXX"],
	"playlistTitles": ["Lake Travis Daily 4K Timelapse"]
}

![example](https://user-images.githubusercontent.com/4943027/218320376-a5b709c4-524b-4059-aa96-36b8bc047dfd.jpg)

**Comment by porjo** [comment]
Try replacing `"privacy": "public"` with `"privacyStatus": "public"` in your JSON file.

**Comment by pgregg88** [comment]
Changing to my json to "privacyStatus": "public" did the trick. Thank you.
