### ISSUE TITLE
Error building OAuth client: bind: address already in use

### ISSUE THREAD

**Issue by pgregg88** [porjo/youtubeuploader#161]
Porjo, thanks again for the great app. This one is likely user error at some level. I appreciate you're not here to teach people how to code. I'd appreciate any insights you might have to aid my troubleshooting.

For context, I've written a python app that creates a daily timelapse video by taking a number of pictures with an IP camera, creates a time-lapse video and a metaJSON file then publishes to YouTube with youtubeuploader.

When I run `./youtubeuploader -filename xxx.mp4 -metaJSON xxx.json` from the command line I'm able to upload videos without any errors.

However, when I attempt to run youtubeuploader as a subprocess within a python function I get the following error (almost always)
`Video Publish failed: 2023/02/24 04:35:25 Error building OAuth client: listen tcp :8080: bind: address already in use`

After I get this error, I run sudo lsof -i :8080 and consistently get this.
```
COMMAND       PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
youtubeup 2644832 pgregg    7u  IPv6 4108920      0t0  TCP *:http-alt (LISTEN)
```
Oddly, after getting this error from my python code... if I run youtubeuploader from the command line and reference the identical -filename and -metaJSON it uploads with no problem. I don't kill the process listed above or anything else.

Additionally, if I use my python script to create and publish a very small video (like a 2 second video) my python function works without error. However, if I use the same python code to create a normal video (2 to 4 min) I get the error every time.

I'm calling youtubeuploader like this...
```
def publish_video(video_path, json_path, logger):
     Try:
          result = subprocess.run(['/home/pgregg/timelapse/youtubeuploader', '-filename', video_path, '-metaJSON', json_path], capture_output=True)
     Except:
            ...
```

I don't have any other services running on this Ubuntu server that use port 8080.

Thank you!

**Comment by porjo** [comment]
My guess is the instance of youtubeuploader running from Python can't find the token file, so is initiating the oauth flow which causes it to listen on port 8080. Try including `-cache` and `-secrets` command line parameters with absolute path names from Python script e.g.
```
result = subprocess.run(['/home/pgregg/timelapse/youtubeuploader', '-filename', video_path, '-metaJSON', json_path, '-cache', <path to token file>, '-secrets', <path to secrets file>], capture_output=True)
```

**Comment by pgregg88** [comment]
@porjo That was it. Thank you very much
