### ISSUE TITLE
add to playlist using cli flag

### ISSUE THREAD

**Issue by jimmyd-be** [porjo/youtubeuploader#164]
I have a script to upload my movies automaticly to Youtube using youtubeuploader. Now I want to upload it to a specific playlist, it looks like it is possible using the metadatafile but I'm not using that.

Can you please add the playlist argument to the program?

**Comment by borbware** [comment]
i'd like to have the same feature. i have to automate this for many video files so having a separate json for every video is very inconvenient...

(the same for the recording date!)

**Comment by porjo** [comment]
New cli flag `-playlistID` has been added in [latest release v24.03](https://github.com/porjo/youtubeuploader/releases/tag/24.03). To upload to multiple playlists at once, just list the flag multiple times e.g. 
```
./youtubeuploader -filename video.mp4 -playlistID xxxx -playlistID yyyy
```
