### ISSUE TITLE
Can I merge it with yt-dlp somehow?

### ISSUE THREAD

**Issue by hasnogaems** [porjo/youtubeuploader#168]
Can I make it so I dowload video with yt-dlp then it automatically auto upload and delete from my hdd after?

**Comment by porjo** [comment]
You could create a simple shell script (bash or Powershell) to call yt-dlp then call youtubeuploader after it.

**Comment by hasnogaems** [comment]
> You could create a simple shell script (bash or Powershell) to call yt-dlp then call youtubeuploader after it.

Can I force file removal from my hdd after the upload finished?
