### ISSUE TITLE
WARNING: input file doesn't appear to be a video. It has content type 'image/png'

### ISSUE THREAD

**Issue by LucianoTheWindowsFan** [porjo/youtubeuploader#170]
Hello.

So when I was trying to use the Windows release, when I was setting a custom thumbnail for the video. I get the following:

> WARNING: input file doesn't appear to be a video. It has content type 'image/png'

The odd part is that my command format seems to be correct, therefore making the issue complicated.

The command format I used in question:

> youtubeuploader -metaJSON [JSON].json -thumbnail "[THUMBNAIL].png" -filename "[VIDEO].mp4"

**Comment by porjo** [comment]
Thanks for reporting the issue. I've pushed a fix in https://github.com/porjo/youtubeuploader/commit/09867f5657f68c47d03ac074a47b2db635a0ced3 - that will be in a future release.

**Comment by porjo** [comment]
Fixed in new release [23.04](https://github.com/porjo/youtubeuploader/releases/tag/23.04)
