### ISSUE TITLE
Also read request.token on default config directory

### ISSUE THREAD

**Issue by AnimMouse** [porjo/youtubeuploader#171]
On version 22.04 it is now possible to omit `-secrets` by placing the client_secrets.json file on `~/.config/youtubeuploader/client_secrets.json` without placing the client_secrets.json file on the current working directory. But request.token still requires to be placed on the current working directory, or use `-cache ~/.config/youtubeuploader/request.token` on the command line.

Reading request.token file on the default config directory just like https://github.com/porjo/youtubeuploader/issues/129#issuecomment-1286426670 is better so that we don't need to specify the request.token file location on the command line.

**Comment by porjo** [comment]
Fixed in new release [23.04](https://github.com/porjo/youtubeuploader/releases/tag/23.04)
