### ISSUE TITLE
Windows and remote ubuntu help

### ISSUE THREAD

**Issue by JackBird15** [porjo/youtubeuploader#183]
Hi, so I have made my request.token and client_secrets.json on my Windows 11 PC. Now I've moved those files to my headless ubuntu server. I'm not sure what to do from here.

**Comment by porjo** [comment]
You need 3 files on your Ubuntu host: `request.token`, `client_secrets.json`, `youtubeuploader` (Linux version). Then run it from command line and see what happens e.g. `./youtubeuploader <filename>`
