### ISSUE TITLE
No acess to "http://localhost:8080/oauth2callback?state=......"

### ISSUE THREAD

**Issue by netsonicyxf** [porjo/youtubeuploader#186]
This is the 1st time to upload video. After running the command, a browser window should popup and prompt you to provide Youtube credentials. I select the google account and allow "youtube uploader" to to have access to my google account. Then the address in the broswer changes to something like "http://localhost:8080/oauth2callback?state=......" and shows "localhost has rejected the connection"

**Comment by porjo** [comment]
Please paste the command line output

**Comment by netsonicyxf** [comment]
youtubeuploader -filename 1.mp4

**Comment by porjo** [comment]
Hmm, that's a strange error. It seems like a network issue, possibly on the localhost (e.g. firewall). Can you try with the debug flag e.g.`youtubeuploader -debug -filename 1.mp4`

**Comment by porjo** [comment]
Closing for now
