### ISSUE TITLE
Ability to authenticate without a browser

### ISSUE THREAD

**Issue by Jaom** [porjo/youtubeuploader#19]
Other uploading scripts provide the user with an alternate way. While opening the browser the script also gives you link (which you can access from any computer) and it's waiting for a response to be pasted into it. Very useful when running script from an environment without proper graphic environment.

**Comment by porjo** [comment]
I've just pushed an update which will fix this for you. See the README file for details:

https://github.com/porjo/youtubeuploader/blob/master/README.md#alternative-oauth-setup-for-headless-clients
