### ISSUE TITLE
Brand Account support

### ISSUE THREAD

**Issue by BillyCroan** [porjo/youtubeuploader#191]
I use several "brand account" subaccounts on youtube to group my uploads by category / intended audience.  

The first time I run it I have to select a google account, and then a brand account.  When I do, I get this error:
Access blocked: youtubeuploader has not completed the Google verification process
Public Meetings
youtubeuploader has not completed the Google verification process. The app is currently being tested, and can only be accessed by developer-approved testers. If you think you should have access, contact the [developer](https://accounts.google.com/b/107094915252974135710/).
If you are a developer of youtubeuploader, see [error details](https://accounts.google.com/b/107094915252974135710/).
Error 403: access_denied

Error 403: access_denied
Request details: access_type=offline response_type=code redirect_uri=http://localhost:8080/oauth2callback state=st1721524691705260447 prompt=consent client_id=72070884660-fdvhqkv34v131bttkq3d27g0q711bufs.apps.googleusercontent.com scope=https://www.googleapis.com/auth/youtube.upload https://www.googleapis.com/auth/youtubepartner https://www.googleapis.com/auth/youtube flowName=GeneralOAuthFlow
[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/production-readiness/brand-verification?hl=en#projects-used-in-dev-test-stage)

if I select my base Google Account and not a brand account, then it seems to link properly.

My original error was slightly different causing me to go into edit the oauth consent screen from internal to external.  It feels like I should add a "test user" for the brand account, but the brand account is not a google id, not an email address so far as I know.

What is the correct way to use brand accounts with youtubeuploader?

Also it looks like the uploads I COULD make to my root account, are locked private for policy violation???
![image](https://github.com/user-attachments/assets/bc7091a7-8835-4491-aaf9-cb5c5f7ed13a)

**Comment by ianb-mp** [comment]
>  youtubeuploader has not completed the Google verification process. The app is currently being tested, and can only be accessed by developer-approved testers

I'm not familiar with 'brand accounts' but the error suggests that verification is required in order to use them via the Youtube API. See link below.

> Also it looks like the uploads I COULD make to my root account, are locked private for policy violation???

By default all 'unverified' accounts will have uploaded videos set to private - see https://github.com/porjo/youtubeuploader/issues/86

**Comment by porjo** [comment]
> youtubeuploader has not completed the Google verification process. The app is currently being tested, and can only be accessed by developer-approved testers

I'm not familiar with 'brand accounts' but the error suggests that verification is required in order to use them via the Youtube API. See link below.

> Also it looks like the uploads I COULD make to my root account, are locked private for policy violation???

By default all 'unverified' API clients will have uploaded videos set to private - see https://github.com/porjo/youtubeuploader/issues/86

**Comment by rickbot-dot** [comment]
> I'm not familiar with 'brand accounts'

think of brand accounts as a ball with a few smaller marbles inside. the ball is the root account and the marbles are brand accounts.

**Comment by porjo** [comment]
Closing for now.

**Comment by AnimMouse** [comment]
youtubeuploader supports brand accounts ever since.
