### ISSUE TITLE
Expiry Never Updates?

### ISSUE THREAD

**Issue by Scoffins** [porjo/youtubeuploader#193]
Hi, just rummaging around the code and noticed that the cached expiry date never gets updated after the first auth. I didn't dig far into it, but I am assuming it would use this to decide whether the access_token has expired and to to use the refresh token to get a new one, right? usually the API returns an expires_in integer (3599 seconds) - I guess your expiry value is meant to be calculated from that every time it uses the refresh token?

I get that it could just use the refresh_token on every request to return a fresh access_token, but I would assume the expiry is meant to make things a little more efficient for when the existing access_token is still valid?

I could be completely wrong about all of this, but thought I'd pick your brains to see if I'm missing something.

**Comment by porjo** [comment]
To be honest, I'm not too sure about this. There are two tokens in `request.token` file - access token, and refresh token.  It seems that the refresh token never expires - see: https://stackoverflow.com/a/8954103 . So I assume the `expiry_date` field is for the  access token ?

Is this causing any problem for you?

**Comment by bmadventures** [comment]
I've the issue regularly. After seven days the upload is failing because of expired access_token. It seems that it never uses the refresh_token to update the access_token.
I thought it's an issue with the `request.token` file permission, but it isn't. Also the debug log looks good until it stops to work. Any other ideas?

**Comment by porjo** [comment]
@bmadventures your issue might be explained by 'testing' mode, see https://github.com/porjo/youtubeuploader/issues/115#issuecomment-1112847059
