### ISSUE TITLE
Retry upload upon a failure

### ISSUE THREAD

**Issue by Jaom** [porjo/youtubeuploader#20]
Sometimes I'm hitting 
> Error 503: Backend Error

(up to 7% of uploads)
It would be nice to have a new parameter `-retry [int]` which would basically mean that if that error occurs the software stars uploading from a scratch a given number of tries. The side effect is that each failure means another copy on the uploaded video list but I suppose everyone would rather have the videos uploaded overnight and delete the corrupted copies rather than having to re-upload some of them.

**Comment by porjo** [comment]
I'm not sure I want to build that into youtubeuploader. 

Why not put youtubeuploader in a script, and check the exit status. If it has a non-zero exit status or you see the 503 error, then re-run it from your script.

**Comment by Jaom** [comment]
You're probably right.
