### ISSUE TITLE
wiki how to install this on linux ubuntu VPS ?

### ISSUE THREAD

**Issue by putuoka** [porjo/youtubeuploader#27]
i want to try this on my linux VPS from ssh access how to install this on linux? is that a clear instruction about this ?

i tried but fail https://i.imgur.com/SophJVH.png

**Comment by porjo** [comment]
Instead of `go get github.com/porjo/youtubeuploader` try `go get -d github.com/porjo/youtubeuploader` instead. This will prevent go trying to compile before `dep ensure` has been run.

If you don't already have `dep` installed, then do that first with `go get -u github.com/golang/dep/cmd/dep`

**Comment by putuoka** [comment]
man.. this is way to hard for me https://i.imgur.com/4JKPjWj.png
stil can't work

**Comment by putuoka** [comment]
sorry sir that's because i don't know how to run this in linux so i follow the instruction on the home page of compile step. could you please share with me how to use this on linux with binaries release?

**Comment by porjo** [comment]
- download this binary: https://github.com/porjo/youtubeuploader/releases/download/1.6.8/youtubeuploader_linux_amd64.gz
- gunzip it  - `gunzip youtubeuploader_linux_amd64.gz`
- run the executable `./youtubeuploader_linux_amd64`
- follow the instructions in the README starting from the heading "Alternative Oauth setup for headless clients" to get an authentication token

**Comment by putuoka** [comment]
WOW Its working great man. Thank you. You the best!!

**Comment by porjo** [comment]
Glad to hear you got it working! :smile:

**Comment by putuoka** [comment]
Hi bro @porjo its me again. I'm forgot how i cant get aunthentication from google now it say site can't be reach. i can't open http://localhost:8080/oauth2callback from my browser. what should i do? should i install xampp?

**Comment by Cinerar** [comment]
@putuoka  
You should use 
```
youtubeuploader  -headlessAuth 
```
set this if host does not have browser available for the oauth authorisation step

**Comment by putuoka** [comment]
@Cinerar sorry that's not my question. i lil bit confused after that headless step we need to open given url in browser to get auth code but it's redirect to localhost:8080 which is not exist on my local. but don't worry i recently figur it out we just need to enter auth code on url after rediretc. this is solved mate. thak you
