### ISSUE TITLE
Return video URL after upload?

### ISSUE THREAD

**Issue by orschiro** [porjo/youtubeuploader#28]
Hey @porjo,

Thanks for your useful binary!

On request:

Can we return the URL of the video after upload? :-)

**Comment by jorisrobijn** [comment]
The ID is returned. You can prepend a fixed string to get to an edit or play page. E.g. my own application that calls youtubeupload detects the ID from the returned text and stores it. Later I can use it to go to the edit or play page for all my uploaded movies. Works well.

**Comment by orschiro** [comment]
@jorisrobijn thanks for the hint! Going to see how I can use the ID. :-)

**Comment by porjo** [comment]
As the video ID can be used in a number of different Youtube URLs, I think it would be better if the user constructs the URL themselves like @jorisrobijn is doing e.g. append the ID to `https://www.youtube.com/watch?v=<videoid>`

**Comment by Cinerar** [comment]
I suggest to change behavior of -q option
I believe it will be better if youtubeuploader will return only video ID when -q is used.

**Comment by porjo** [comment]
Do you mean `-quiet` option? Currently that stops the progress output, but all other messages including video ID are printed.

**Comment by Cinerar** [comment]
Yeah but i mean video ID should be the only one output to stdout.
Without other symbols so there will be no need on the other end to parse it.
