### ISSUE TITLE
Add multiple playlist?

### ISSUE THREAD

**Issue by inrepublica** [porjo/youtubeuploader#29]
Is it possible to add multiple playlist in the metaJSON file?

Example:
`"playlistId":  ["xxxxxxxxxxxxxxxxxxxxxxxxxxx", "yyyyyyyyyyyyyyyyyyyyyyyy"]`

**Comment by porjo** [comment]
I've added a new option for this now (note the trailing 's' on `playlistIds`)
```
"playlistIds": ["xxxxxxxxxxxxxxxxxxxxxxxxxxx", "yyyyyyyyyyyyyyyyyyyyyyyy"]
```
See the [latest release](https://github.com/porjo/youtubeuploader/releases)

**Comment by inrepublica** [comment]
Thanks a lot! ;-)
