### ISSUE TITLE
Add an option to specify the language of the video

### ISSUE THREAD

**Issue by inrepublica** [porjo/youtubeuploader#30]
Is it possible to add an option to specify the language of the video? Maybe in the metaJSON?
I don't know if youtube API contain this parameter, maybe : "defaultLanguage": string (https://developers.google.com/youtube/v3/docs/videos)

**Comment by porjo** [comment]
I've pushed a [new release](https://github.com/porjo/youtubeuploader/releases/tag/18.05) which includes this feature. Add `language` to the metaJSON file - the value can be any of the 2 letter language codes ([ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)) e.g. 'es' for Spanish, 'fr' for French etc. You can also specify a region e.g. 'fr-CA' for French Canadian

**Comment by inrepublica** [comment]
Thanks!
