### ISSUE TITLE
Add new parameter for user contribution

### ISSUE THREAD

**Issue by inrepublica** [porjo/youtubeuploader#31]
I don't known if youtube allow this, but a new parameter for user contribution would be great.
User contribution is in "advanced settings" in youtube:
![drawing](https://i.imgur.com/JA4C3D1.png)
Capture is in french but in english the position must be the same. In english this option is probably named like this: "Allow Internet users to contribute to the translation of titles, descriptions and subtitles".

**Comment by porjo** [comment]
Looks like it is not yet supported by the Youtube API:

https://stackoverflow.com/questions/43970784/videos-uploaded-through-youtube-api-v3-are-uploaded-with-community-contributions

**Comment by porjo** [comment]
I'll close this now. It can be reopened once Youtube API adds support.
