### ISSUE TITLE
how to get -categoryId  parameter??

### ISSUE THREAD

**Issue by gitscamI** [porjo/youtubeuploader#34]
hello,everybody, how to get the video's category and Id whice I will to  upload?

**Comment by Jaom** [comment]
https://gist.github.com/dgp/1b24bf2961521bd75d6c

**Comment by Jaom** [comment]
Also:
https://stackoverflow.com/questions/17698040/youtube-api-v3-where-can-i-find-a-list-of-each-videocategoryid

**Comment by gitscamI** [comment]
Thank you,Jaom

**Comment by porjo** [comment]
Youtubeuploader could probably request this list from the Youtube API, however as the list rarely changes (?) it might be just aswell to refer to a static list like the one supplied.

**Comment by Jaom** [comment]
@porjo  it's region specific
