### ISSUE TITLE
upload failed many times

### ISSUE THREAD

**Issue by putuoka** [porjo/youtubeuploader#36]
it took me 4 times to try for completely successful upload

![image](https://user-images.githubusercontent.com/20880839/37877055-cece8f90-3087-11e8-866a-4155f360587b.png)

**Comment by Jaom** [comment]
Can't process file not failed upload.
It sounds like a server side issue - you should consult:
https://support.google.com/youtube/answer/1722171?hl=en

Have you uploaded SAME file every single time? It's awkward that it got processed after all.

**Comment by porjo** [comment]
Uploads are working for me with latest `youtubeuploader` version. It's possible there was a temporary backend issue with Youtube at that time? Have you tried again more recently?

**Comment by putuoka** [comment]
@Jaom @porjo  yes exactly i'm uploading the same file because i see notice failed upload so i try and try again to upload ti success but in the last all 4 video file uploaded successfully. the failed status updated after ouple of minutes and they all successfully uploaded with notice "duplicate file"

it seem server side issues. not sure.
