### ISSUE TITLE
No progress indication

### ISSUE THREAD

**Issue by Jaom** [porjo/youtubeuploader#38]
Command:
`youtubeuploader -cache request.token  -filename "xxxxxx/output.mkv" -metaJSON meta.json -secrets client_secrets.json -chunksize 0`

Output:
`Uploading file 'xxxxxx/output.mkv'...
Upload successful! Video ID: [properVideoID]
2018/03/27 19:38:11 Error adding video to playlist: error retrieving playlists: googleapi: Error 403: Insufficient Permission, insufficientPermissions`

Even though `-quiet` is not set I still get no current progress. This is using `Youtubeuploader version: 18.07`.

PS
I wouldn't worry with the error adding to playlist - I'll will fix permissions later.

**Comment by porjo** [comment]
The reason you're not seeing progress is due to `-chunksize 0` which is effectively bypassing the custom transport which produces the progress output. It's possible it also bypasses the ratelimiting - can you confirm? I'll see if that can be fixed.

**Comment by porjo** [comment]
This is fixed in latest release 18.08
