### ISSUE TITLE
Headless authorization error

### ISSUE THREAD

**Issue by Jaom** [porjo/youtubeuploader#39]
youtubeuploader  -filename "xxxxxx/output.mkv" -metaJSON meta.json -secrets client_secrets.json -chunksize 0 -headlessAuth

`Visit the URL for the auth dialog: [link here]
Enter authorisation code here: `

I copy and paste the link to browser on **another PC** which is fine.
I authorize the app to do things which is fine.

Then I get moved to:
`http://localhost:8080/oauth2callback?state=[state]&code=[code]#`
_(state and code being some proper values)_
Then I get `ERR_CONNECTION_REFUSED` on my browser. I suppose there is nothing listening on port 8080 even less replying on **another PC**?

**Comment by porjo** [comment]
I've justed tested the headless auth process using latest version and it worked for me. Make sure you follow the [instructions from the README](https://github.com/porjo/youtubeuploader#alternative-oauth-setup-for-headless-clients) exactly. Note: if you have an existing `client_secrets.json` file, you should remove that before running `-headlessAuth`.

**Comment by Jaom** [comment]
Yup, it works. No idea how I should expect that I need to delete the client_secrets file. Now when I think about it it makes sense but It's mentioned nowhere.

**Comment by porjo** [comment]
Sorry, what I said before isn't accurate. What I should have said is that you **must** have a `client_secrets.json` file and it must contain the correct details generated by the steps in the oauth instructions - these details will be different depending on which instructions you follow - normal, or headless.

**Comment by quydox** [comment]
hello I run command:

./youtubeuploader -headlessAuth

But output are help strings

**Comment by Jaom** [comment]
You have to specify filename:
`./youtubeuploader -headlessAuth -filename test.mp4`

Sadly `test.mp4` needs to exist and be a video file.
