### ISSUE TITLE
Uploading from another machine than localhost

### ISSUE THREAD

**Issue by Konstantinusz** [porjo/youtubeuploader#4]
I would like to upload videos from my VPS, so I tried to set on Goolge dev console the VPS IP address as authorized redirect URI. It says: "Invalid Redirect: http://my-IP-address:8080/oauth2callback must end with a public top-level domain (such as .com or .org)"
On my VPS there is no GUI and browser, only SSH and CLI. How can I use this application to upload videos from the VPS if I can paste the long authorization URL only on another machine?

**Comment by porjo** [comment]
The README says this

> To run the utility on a headless-server, generate the token file locally first, then simply copy the token file along with youtubeuploader and client_secrets.json to the remote host.

Have you tried that?

**Comment by Konstantinusz** [comment]
Oh, thanks. I didn't know there is a readme too, but I managed to find out this way meanwhile. Very useful utility, it also can upload video stream from a FIFO, unlike other similar CLI applications found on github. This way it is possible to upload dynamic content without saving to huge local file.
