### ISSUE TITLE
how to set the  parameter "playlistIds"

### ISSUE THREAD

**Issue by gitscamI** [porjo/youtubeuploader#40]
how to set the  parameter "playlistIds"?  "playlistIds":  ["xxxxxxxxxxxxxxxxxx", "yyyyyyyyyyyyyyyyyy"]

what means the playlistIds?

**Comment by Jaom** [comment]
https://www.youtube.com/playlist?list=PLBiPNxqFKPZIWTooh9mCq3rIphK86Almm 

Playlist ID is the ID that follows "list" in the url of a playlist.

`"playlistIds": ["PLBiPNxqFKPZIWTooh9mCq3rIphK86Almm"]`

**Comment by gitscamI** [comment]
hi,I setup the playlistIds as you said, but the video still cant put into playerlist......

**Comment by porjo** [comment]
@gitscamI what is the output from `youtubeuploader` when you attempt to add to a playlist?

**Comment by porjo** [comment]
I'll close this now and reopen again if needed.
