### ISSUE TITLE
How to upload video without authorization?

### ISSUE THREAD

**Issue by saisaixv** [porjo/youtubeuploader#43]
Run on an operating system without a graphical interface.

**Comment by Cinerar** [comment]
https://github.com/porjo/youtubeuploader#alternative-oauth-setup-for-headless-clients

**Comment by saisaixv** [comment]
No,I'm trying to avoid the need for human intervention.

**Comment by porjo** [comment]
> No,I'm trying to avoid the need for human intervention.

@saisaixv getting an authentication token from Google only happens once, the first time youtubeuploader is run. That requires human intervention, and I'm not aware of a way around that. Once you have the token, then no further human intervention is required - youtubeuploader can be run in a scripted environment using that token.

**Comment by saisaixv** [comment]
How to use ApiKey?Do not use oauth2!

**Comment by porjo** [comment]
@saisaixv as described in the Youtube developer doco here https://developers.google.com/youtube/v3/getting-started oauth2 is the only authentication available for Youtube API v3 (which youtubeuploader uses)

I will close this issue now.
