### ISSUE TITLE
i can't understand how to use

### ISSUE THREAD

**Issue by FateRui** [porjo/youtubeuploader#44]
i can't understand how to use
1、Run youtubeuploader for the first time, passing the -headlessAuth parameter
2、Copy-and-paste the URL displayed and open that in a browser
3、Copy the resulting authorisation code and paste that into the youtubeuploader prompt: "Enter authorisation code here:"

please tell me how to use it

**Comment by porjo** [comment]
1. Run the command `youtubeuploader -headlessAuth -filename <yourfile>` from the command prompt
Soon afterwards a URL will be displayed at the command prompt
2. copy and paste the URL displayed above, and paste it into your web browser
3. when the page has loaded, it will require you to login into Google and agree to give access to youtubeuploader. Once that's done, it will display an authorisation code. Copy the code from the browser and paste it to the command prompt where youtubeuploader is running

I hope that helps.

**Comment by FateRui** [comment]
i am ok  Thank you !!!
