### ISSUE TITLE
error when uploader

### ISSUE THREAD

**Issue by gitscamI** [porjo/youtubeuploader#46]
the error information:
2018/05/30 09:52:24 Error making YouTube API call: googleapi: Error 400: The req
uest metadata is invalid., invalidVideoMetadata

the meta json file:
```json
{
  "title": "my test title",
  "description": "my test description",
  "tags": ["test tag1", "test tag2"],
  "privacyStatus": "public",
  "embeddable": true,
  "license": "creativeCommon",
  "categoryId": "22",
  "playlistIds":  ["PL-i_TB4my4RXO2_vwBW_qxzg-gZjUeYfBP"],
  "language":  "cn"
}
```

I had normal uploader using the metafile ,but now ,it suddenly reports the error, don't know what's wrong

**Comment by gitscamI** [comment]
if there is a bug, I remove playlistIds in metafile, it can upload. playlistIds cant work

**Comment by porjo** [comment]
Hmm, that's very strange. I've just tested using `playlistIds` with latest youtubeuploader and it worked for me. Unfortunately the Youtube API doesn't give a more specific error message under these conditions, so we are left to guess at what the problem could be :disappointed: 

Do you get the error if you remove all other options from the meta JSON file, but leave only `playlistIds`?

**Comment by gitscamI** [comment]
porjo,thanks very much .
after see your reply,I try many times ,I found it is the last line, I change language to en, everythin is ok

**Comment by porjo** [comment]
ah, ok. There are only a limited number of supported languages, unfortunately `cn` isn't one of them. I think it should be possible to do a lookup to the API to check if the language is supported. I'll will try to include that in a future release.
