### ISSUE TITLE
Problem to add a playlist

### ISSUE THREAD

**Issue by inrepublica** [porjo/youtubeuploader#47]
Hello,

I have a little problem when i try to add a playlist.
I try this command:
`youtubeuploader.exe -filename "test.avi" -metaJSON "test.json" -thumbnail "test.jpg"`
With this JSON:
```json
_{ "title": "test",
 "description": "test",
 "tags": ["test1", "test2"],
 "privacyStatus": "private",
 "embeddable": true,
 "publicStatsViewable": true,
 "recordingdate": "2013-04-20",
 "playlistIds": ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-T"],
 "language":  "fr"
}_
```

I have this result:
```_Uploading file 'test.avi'...
Progress:   203.10 kbps, 223344138 / 223344138 (100.000%) ETA       0s
Upload successful! Video ID: xxxxxxx
Video added to playlist 'Playlist test' (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
2018/06/28 12:51:11 Error adding video to playlist: playlist ID 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-T' doesn't exist_
```

The first playlist is ok, but the second no. My second playlist has a weird form with a "-": xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-T
Another problem is when a playlist is not added, the thumbnail is not uploaded.

Sorry for my english ;-(

**Comment by porjo** [comment]
Youtubeuploader will create a playlist if it doesn't exist, but only if you specify the playlist title. Specifying a playlist ID for a playlist that doesn't exist will result in the error `Error adding video to playlist: playlist ID 'xxx' doesn't exist`

Are you sure that playlist with ID `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-T` exists and is associated with the Youtube account which youtubeuploader is authorised to modify?

**Comment by inrepublica** [comment]
I've tested with 3 another playlist, no problem. Just this fuck**g playlist!!!
It's the only one of my playlist with "-" in his name... I don't no why...

**Comment by inrepublica** [comment]
My playlist: https://www.youtube.com/playlist?list=PLg5YS7OLSWWp1g2aBbI76W53p58IYg4-T

**Comment by porjo** [comment]
I see your Youtube channel has another playlist with ID `PLg5YS7OLSWWoj4ck3_efjhRORVRHbWj-T` - have you tried uploading to that one?

**Comment by inrepublica** [comment]
I just tried with this playlist (PLg5YS7OLSWWoj4ck3_efjhRORVRHbWj-T), no problem...

**Comment by porjo** [comment]
ok, I think we can rule out the "-" in the id being a problem. Could you try using [tokland/youtube-upload](https://github.com/tokland/youtube-upload) to upload to the problem playlist? If that works OK, then that would confirm the problem is with youtubeuploader

**Comment by inrepublica** [comment]
Ok I've tested with Youtube-upload:
`youtube-upload --title="test" test.mkv --privacy="private" --playlist="Le dessous des cartes"
Using client secrets: /usr/local/share/youtube_upload/client_secrets.json
Using credentials file: /home/inrepublica/.youtube-upload-credentials.json
Start upload: test.mkv
100% |#############################################################| 125.3 KiB/s
Video URL: https://www.youtube.com/watch?v=eXh8aOb0UpI
Adding video to playlist: PLg5YS7OLSWWp1g2aBbI76W53p58IYg4-T
eXh8aOb0UpI
`
That's ok, the video is in "Le dessous des cartes" playlist.
