### ISSUE TITLE
meta.json vs command line option

### ISSUE THREAD

**Issue by Jaom** [porjo/youtubeuploader#49]
I think that there is no rule which parameters can be passed as an opntion and which need to be run through meta.json. I think that everything should be possible via both ways or there should be some kind of logic to it.

(I'd actually benefit from command line option for playlist id which is not available but that's beside the point)

**Comment by porjo** [comment]
The command line came first, then as more options were being added they went into `meta.json`. I'm not opposed to having all options available on the command line. PR welcome.
