### ISSUE TITLE
Error building OAuth client: expecting state 'st1538925745826976579', received state ''

### ISSUE THREAD

**Issue by ostrolucky** [porjo/youtubeuploader#52]
```
$ ./youtubeuploader_linux_amd64 -filename video.mp4
Your browser has been opened to an authorization URL.  This program will resume once authorization has been provided.
2018/10/07 17:24:02 Error building OAuth client: expecting state 'st1538925842172918412', received state ''
```

Browser is opened with authorization url, but youtubeuploader immediately closes with above error

version 18.3

**Comment by ostrolucky** [comment]
hmm it works now, closing

**Comment by dan-leech** [comment]
I have this issue in 18.14. It comes only in run mode, while debuging all works fine.
I downloaded json from google.

**Comment by dan-leech** [comment]
maybe it will help in debugger callbackCh gets two requests one with code then with code ""

**Comment by dan-leech** [comment]
`go http.Serve(listener, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		cbs := CallbackStatus{}
		cbs.state = r.FormValue("state")
		cbs.code = r.FormValue("code")
		if cbs.code != "" {
			callbackCh <- cbs // send code to OAuth flow
		}
		listener.Close()
		w.Header().Set("Content-Type", "text/plain")
		fmt.Fprintf(w, "Received code: %v\r\nYou can now safely close this browser window.", cbs.code)
	}))`

This fixes issue
