### ISSUE TITLE
Read port to listen on for auth from client_secrets instead of hardcoding it

### ISSUE THREAD

**Issue by ostrolucky** [porjo/youtubeuploader#53]
You hardcode port 8080 to listen to, but this is the port I use for my service.

**Comment by porjo** [comment]
I've added a `-oAuthPort` flag now which you can use to specify a port other than 8080 - see latest release: https://github.com/porjo/youtubeuploader/releases/tag/18.14

**Comment by ostrolucky** [comment]
my idea was to read it automatically from json file, but this is good enough, thanks!
