### ISSUE TITLE
how can i upload subtitles (cc) for a video?

### ISSUE THREAD

**Issue by wolfram77** [porjo/youtubeuploader#55]
i am using youtubeuploader to automatically upload wikipedia text-to-speech videos. one person asked me to upload such videos with subtitles. youtube has such a feature where i can add the text, and it will automatically align the time for the text. how can i upload such a text file through youtubeuploader? please help.

**Comment by wolfram77** [comment]
videos are like this: https://www.youtube.com/watch?v=djNB_XVfoIk

**Comment by porjo** [comment]
It looks like it is possible - see https://github.com/evertonstz/youtube-upload however youtubeuploader does not support that yet

**Comment by wolfram77** [comment]
then lets make it happen! i am learning golang, and then will go through youtube api and your code. thanks.
