### ISSUE TITLE
how to get video ID after upload

### ISSUE THREAD

**Issue by rbsns** [porjo/youtubeuploader#58]
Thanks for this awesome software.

As @Cinerar said at #28, would be great if `-quiet` option return only the video ID with exit code 0 (zero) on success and 1 on error, redirecting the error message to stderr and the video ID to stdout.

Not a bug or something important, as today we can achieve this using `sed`:

```bash
X=`youtubeuploader -filename ${FILE}`
ID=`echo $X | sed -E 's/.*Video\ ID\:\ (.+).*/\1/'`;
``` 

But It's a good way to use `youtubeuploader` with bash scripts or other softwares.

Best regards!

**Comment by porjo** [comment]
I don't want to create a dependency on the console output being formatted a certain way.

Instead, how about a new command line flag that takes a filename: when the video is successfully uploaded, youtubeuploader would write the [Video](https://godoc.org/google.golang.org/api/youtube/v3#Video) object into that file as a JSON string. You can then parse that and pull out the video ID.

**Comment by jorisrobijn** [comment]
I understand the concern about the freedom to change the output. However, I also use it in a similar way when I do automatic uploads. If the upload is OK (judged by the exit code) I parse the output and I search for "Video ID: ". I think if you limit this to specific things only, it does not limit your freedom (much) but it does allow automated use for things like the video ID. To be honest, I think writing the ID to a file is a bit of an ugly solution.

**Comment by Scoffins** [comment]
Output the uploader command to a txt file, preferbly using "tee" (Try UnxUtils if on Windows) then parse that file with:
`for /f "tokens=2 delims=:" %%A in ('type "C:\path\to\output.txt" ^| findstr "Video ID"') do set youtube=%%A`

Then you've got the YouTube ID by echoing %youtube:~1%
Hope this helps.

**Comment by Jaom** [comment]
> Instead, how about a new command line flag that takes a filename: when the video is successfully uploaded, youtubeuploader would write the [Video](https://godoc.org/google.golang.org/api/youtube/v3#Video) object into that file as a JSON string. You can then parse that and pull out the video ID.

I like the idea. 
(discussing the issue here as requested https://github.com/porjo/youtubeuploader/issues/72 )

**Comment by porjo** [comment]
I've just pushed release 20.04 with `-metaJSONout` flag. The 'Video' object returned from Youtube will get written to that file after a successful upload. It contains an `id` field containing the video ID.
