### ISSUE TITLE
Add notifySubscribers parameter

### ISSUE THREAD

**Issue by jouven** [porjo/youtubeuploader#59]
https://developers.google.com/youtube/v3/docs/videos/insert#notifySubscribers
Could this be added?
I find strange that a tool which allows to spam uploads pretty easily doesn't have the option to not spam the user feed heh.

**Comment by porjo** [comment]
Yes it can be added. To clarify, you want to be able to disable sending notifications?

**Comment by jouven** [comment]
Yes

**Comment by porjo** [comment]
I've uploaded a [new release](https://github.com/porjo/youtubeuploader/releases) with a `-notify` flag. To retain current behaviour the setting defaults to `true` - to disable notifications specify `-notify false`
