### ISSUE TITLE
Error when building from source on Raspberry Pi

### ISSUE THREAD

**Issue by jrc03c** [porjo/youtubeuploader#6]
Hey! I'm trying to compile from source on a Raspberry Pi and I'm getting this error:

```
# google.golang.org/api/googleapi
../go/src/google.golang.org/api/googleapi/googleapi.go:289: u.RawPath undefined (type *url.URL has no field or method RawPath)
# golang.org/x/net/context/ctxhttp
../go/src/golang.org/x/net/context/ctxhttp/ctxhttp_pre17.go:36: req.Cancel undefined (type *http.Request has no field or method Cancel)
```

Any thoughts?

**Comment by porjo** [comment]
It should 'just work' if you have a recent version of Go. What version are you using? (run `go version` to check).

I've uploaded binaries for armv6 + armv7 to the [releases page](https://github.com/porjo/youtubeuploader/releases) now if you'd like to try those instead of building yourself.

**Comment by jrc03c** [comment]
Hey! Thanks for the binaries; armv6 worked for me! Also, I had installed Go from the Ubuntu / Raspbian repositories, which gave me `go1.3.3 linux/arm`. I saw that you updated your README to indicate that I need v1.6+, so I'll check that out sometime. Thanks!
