### ISSUE TITLE
URL  HTTP Header  options required.

### ISSUE THREAD

**Issue by sroon** [porjo/youtubeuploader#61]
Hello,

When i use URL as a filename to upload videos,there is a problem.

Sometime the URL requires more information to get remote service,like Cookie,Authorization,User-Agent,Referer, etc.

So,may be there should be an option to change the default http headers,or add new ones?

Thanks for your job.

**Comment by porjo** [comment]
youtubeuploader supports piping of data, so you could use curl to do the download, then pipe the output of curl to youtubeuploader:

```
curl -H <custom header> https://<remote>/<file> | ./youtubeuploader -filename -
```
