### ISSUE TITLE
Does this tool support uploading from a pipe?

### ISSUE THREAD

**Issue by YellowOnion** [porjo/youtubeuploader#65]
can I do something like `ffmpeg -i test.mp4 -f mkv - | youtubeuploader -filename -` to save my self time?

**Comment by porjo** [comment]
Not currently supported, however sounds like a worthwhile addition to make.

**Comment by YellowOnion** [comment]
So update, the current build doesn't support pipes, but if you compile it with msys2, I can use mkfifo and anonymous pipes in bash!

**Comment by YellowOnion** [comment]
Actually nevermind, it looks like I got an identically named plain old file that was uploaded.

**Comment by YellowOnion** [comment]
Well I got pipe support working with about 3 lines changed (simply return os.Stdin instead of file), but I hit the stupidly low 10,000 unit quota, while on the 3rd attempt at uploading, so don't really know if it's working all that well.
