### ISSUE TITLE
New-Line Break (/n) Not Working

### ISSUE THREAD

**Issue by Scoffins** [porjo/youtubeuploader#67]
New line breaks don't work (tested using meta json file as input) they just show "/n" as part of the video description.

Update: I meant \n doesn't work.

**Comment by porjo** [comment]
Try `\n` instead

**Comment by Scoffins** [comment]
Sorry, \n is what I mean. It doesn't work.

**Comment by nalyk** [comment]
Confirmed, using on a Linux amd64 machine. Having the same issue.

**Comment by Scoffins** [comment]
It doesn't work from metaJSON for me. I'm running Windows 7 64bit.

**Comment by Scoffins** [comment]
Update: Nevermind, \n works perfect. I was accidentally encoding it with PHP's json_encode. Sorry about that, silly mistake.

**Comment by porjo** [comment]
@nalyk I've just pushed a commit which will expand newlines for CLI `-description`. Future builds will include this.
