### ISSUE TITLE
Daily Quota Makes this impractical

### ISSUE THREAD

**Issue by TheDemystifier** [porjo/youtubeuploader#68]
Uploaded about 4 videos and that's it! Quota Exceeded!
So much for the 100 videos/day via the website.

**Comment by porjo** [comment]
I suspect you're amongst a small minority of people who need upload more than 4 videos per day. Have you investigated running multiple instances using different API tokens?

**Comment by jorisrobijn** [comment]
Most recently I did many uploads was last June 21 to 23. I uploaded more than 300 videos in those 3 days. Maybe the limit you are encountering is based on things like the number of subscribers, number of years being member or something like that. Check around on the youtube forums and keep us informed if you found something.

Anyway, it's not an issue with youtubeuploader, it does that just fine.

**Comment by Scoffins** [comment]
This is a quota limit on your account, not an issue with youtubeuploader.
View your Google API quotas here: https://console.developers.google.com/iam-admin/quotas

**Comment by TheDemystifier** [comment]
I wonder, isn't it possible to use the Service account OAuth instead of Console API tokens ?
I mean when you're prompted to give access to your account, and you're given an approvalCode that you paste into the app. This is what [GDrive](https://github.com/gdrive-org/gdrive) does and It allows you to upload loads of videos to Google Drive with no quota limit counter.
It could at least be provided as an option.

**Comment by Jaom** [comment]
There is poorly documented limit of 100 videos per day which is independent of quota.
The quota itself used to be 1,000,000 around 3 years ago, a year ago it was around 100,000 and now it's 10,000 for a new project. They also seem to disable the API within the project rather aggressively so it's hard to retain those higher numbers.

It's rather frustrating. On top of that the previous form for requesting higher quota was impossible to fill (it was protected by reCaptcha v1 which was shut down by Google so it was always failing...). I suppose this tells enough how (not)important this is for anyone at YouTube. Eh...

**Comment by TheDemystifier** [comment]
I have one question though! What if you use this as part of a Desktop app. You can't tell end-users to go to the Developer Console to create their API token. Right ?
I used an app called 'Free YouTube Uploader' back with Win7 a few months ago and it never asked me for an API token or anything. Just a sign-in to the YouTube account!

**Comment by porjo** [comment]
@TheDemystifier  I'm not sure how that other tool achieves what it does without API token, possibly by 'screen scraping'? Given that most people have one Google account they use for everything, I think it would be very dangerous to give a 3rd party app those credentials.

I will close this issue now, as I think the question of quota limits has been answered.

**Comment by jorisrobijn** [comment]
I wanted to let you guys know I did get my quota reset to 1 mln again. It took 3 months and my several different approaches, but finally the request was approved. Looking at the response time, it appears they are quite busy with API things.  And they do require you to respond within 3 business days.
Now I have to make sure I always upload a (dummy) video at least every 90 days, or we might loose access again...

**Comment by Jaom** [comment]
My quota is 2mln. There is still limit (independent) of 100 videos per 24h or so.
It took half a year for them to approve the increased quota. And they've failed to actually update it after approval so I had to make a ticket again (!) just to tell them that they did not deliver on the promise. This took 3 days.

Also i had to reply a number of times within 3 business days (which is bullshit given that they gonna send it on a random day within 6 months...) and it seems more like they're looking for reasons to deny you the quota rather than verify you (so expect step by step answering to every doubt they have, rather than a long list of doubts in one mail).

They do approve the quota though. Even for closed, headless servers, with no UI and without demo (I'm not inviting anyone to my VPS...). Even though when you fill the form you don't feel like it's possible. Heh.

**Comment by jorisrobijn** [comment]
Yes, I specified similar things. In my case a PC that is on only during events, and requires a login.
They don't understand what command line tools are at all, it seems judged on their comments. They always assume use via a website, even if you mention twice in your explanation that it's a command line tool that is not accessible from outside.

**Comment by jorisrobijn** [comment]
1 mln is one million points of quota per day. Each upload costs, what was it, 1600 points I think. 
I'm still uploading dummy video's from a batch file every few months to keep access. Works.
