### ISSUE TITLE
Binaries report `Youtubeuploader version: 18.15-6-g9d8781e` for v19.02

### ISSUE THREAD

**Issue by Jaom** [porjo/youtubeuploader#69]
Both Windows .zip and linux.tar.gz binaries report:
`Youtubeuploader version: 18.15-6-g9d8781e`
after `Youtubeuploader -v`

**Comment by porjo** [comment]
Thanks, looks like I forgot to tag the latest commit prior to running the build. `18.15-6` is 18.15 plus 6 commits, which is the same commit as 19.02! :smile: 

It'd be good to have an automated check to ensure that the latest commit has a tag prior to building. Not sure the best way to do that and keep it simple.
