### ISSUE TITLE
Headless w/ SSH

### ISSUE THREAD

**Issue by jrc03c** [porjo/youtubeuploader#7]
Hey, I have one other little problem. I'm using my Raspberry Pi in headless mode. When I run your program, it generates the link that I can open in the browser to authorize the app to work on behalf of my account. Since I'm SSH'd into the RPi, I can see the link and copy it into the browser in my host machine, but the redirect fails (since it's redirecting to `localhost`). I tried changing the `client_secrets.json` file so that the `redirect_uris` pointed to `http://localhost:8080/oauth2callback`, but then I got errors when I tried to open the link in the browser. I also tried running the program on my host machine and then copying the `request.token` file over to the RPi, but that didn't seem to do anything either. I even went so far as to install the `links` command line web browser on my RPi and tried to open the link in it, but the redirection requires JavaScript, which the `links` browser doesn't do. Any recommendations?

**Comment by porjo** [comment]
Confirm it works on your desktop/laptop first, then copy the *.json files over to the PI

**Comment by jrc03c** [comment]
Hm...I copied over the client_secrets.json file and the request.token file. Do I need any other files?

**Comment by porjo** [comment]
Have you confirmed it definitely works on your desktop first i.e. have you tried to actually upload a file?
Also, what output do you get when you run it on the Pi afterwards?

(I've added Windows 64bit build in case you don't have linux on your desktop)

**Comment by jrc03c** [comment]
Yes, I did actually upload two different files from my laptop successfully. On the Pi, it just keeps showing the "help" stuff:

```
You must provide a filename of a video file to upload
  -cache string
    	Token cache file (default "request.token")
  -category string
    	Video category
  -description string
    	Video description (default "uploaded by youtubeuploader")
  -filename string
    	Filename to upload. Can be a URL
  -keywords string
    	Comma separated list of video keywords
  -privacy string
    	Video privacy status (default "private")
  -quiet
    	Suppress progress indicator
  -ratelimit int
    	Rate limit upload in KiB/s. No limit by default
  -secrets string
    	Client Secrets configuration (default "client_secrets.json")
  -title string
    	Video title (default "Video Title")

```

**Comment by porjo** [comment]
Can you paste the whole command line including arguments? Also, are the *.json files in the same directory as `youtubeuploader`?

**Comment by jrc03c** [comment]
Well, I don't know what was wrong before. But I re-did all of the steps you recommended, and it cooperated. I think it might've been something about the fact that I was abbreviating the command. I did:

```./you* -filename cut4.avi```

instead of:

```./youtubeuploader -filename cut4.avi```

Sorry to have wasted your time! Thanks for the great program!

**Comment by porjo** [comment]
Does the current directory contain the file `youtubeuploader.go`?

If so then `./you* -filename cut4.avi` would actually expand to `./youtubeuploader ./youtubeuploader.go -filename cut4.avi`which isn't a valid way to invoke the command 😢 

> Sorry to have wasted your time! Thanks for the great program!

That's OK, I'm glad you find it useful

**Comment by jrc03c** [comment]
Right, yeah, I thought of that, but I really had no other files in the directory. I just had the youtubeuploader, the client_secrets.json, the request.token, and the cut4.avi.
