### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Sammeeey** [porjo/youtubeuploader#70]
I did the setup as described.
Then I tried to upload a .mp4 file (from the youtubeuploader directory) like this:
```
youtubeuploader -filename How_Google_Search_Works.mp4
```

And I just get this error:

```
panic: runtime error: index out of range

goroutine 1 [running]:
main.readConfig(0xc000070de0, 0x3, 0x3, 0x0, 0xa, 0x30000)
        /home/ian/go/src/github.com/porjo/youtubeuploader/oauth.go:142 +0x560
main.buildOAuthHTTPClient(0x7f39c0, 0xc000070db0, 0xc000070de0, 0x3, 0x3, 0xc000070d80, 0x7f39c0, 0xc000070db0)
        /home/ian/go/src/github.com/porjo/youtubeuploader/oauth.go:178 +0x64
main.main()
        /home/ian/go/src/github.com/porjo/youtubeuploader/youtubeuploader.go:121 +0x3a7
```

Does not matter what I do or which flags I use - I always get this error.
**Does someone know how to fix it?**

**Comment by porjo** [comment]
Thanks for the report. It looks like a bug on Google's developer console causing the 'Authorised Redirect URIs' to be dropped when a project is created initially (I just tried creating a new project and saw the same issue). You can edit the project and add the redirect URI afterwards. I've sent a feedback report to Google about that. I've also pushed a [new release]( https://github.com/porjo/youtubeuploader/releases/tag/20.02) which will set the default redirect URL if none is found.

**Comment by Sammeeey** [comment]
> 
> If you're comfortable editing JSON, the simplest fix for you will be to edit your `client_secrets.json` file and add the following line:
> 
> ```
> "redirect_uris": ["http://localhost:8080/oauth2callback"]
> ```
Found another solution (directly from the YouTube-API) meanwhile.
But I just tested your solution @porjo and it works fine for me.
