### ISSUE TITLE
Grab Video ID after upload

### ISSUE THREAD

**Issue by Scoffins** [porjo/youtubeuploader#72]
In CMD/BATCH, would it be possible to retrieve the video ID after successful upload? Either as a variable or outputted to file? Maybe even update the input json file with a new VideoID field?

Thanks.

**Comment by Jaom** [comment]
It was reported before: https://github.com/porjo/youtubeuploader/issues/28
Apparently you're supposed to capture the videoID from the console.

I don't like it either. I'd also be happy to have it changed. :D

**Comment by porjo** [comment]
Let's use #58 to discuss video id
