### ISSUE TITLE
unknown filename & Default tags,description

### ISSUE THREAD

**Issue by alx-xlx** [porjo/youtubeuploader#73]
First off all I would say **Thank you for this tool**

1. whenever i upload a video using this tool the filename area in the video dashboard shows "Filename: unknown"
![l1WELJqrkp](https://user-images.githubusercontent.com/42188371/73133457-dbf33f80-404e-11ea-95f7-bd5188d18d44.png)

2. i have set some Default tags & description in my youtube dashboard, but they do not show in the video that I upload using this tool.

How do I fix these two problems.

**Comment by porjo** [comment]
I tried to get the filename to be set, however could not get it working. The API appears to support this, however not for uploads but for fetching details of existing videos. When I specify the `fileDetails` part I get error about 'unexpected part'.

**Comment by alx-xlx** [comment]
after googling, i found out that this is a known bug for a very long time & youtube has not yet fixed it.
I think **they will never fix it**, this way they know who uploads video using API and who through their browsers
