### ISSUE TITLE
google api limits

### ISSUE THREAD

**Issue by pc10201** [porjo/youtubeuploader#78]
I create an new project and api.

Api has 10000 units a day.
Only upload 6 videos.

Can you make a new program to upload videos with http cookies or automate broswer?

**Comment by porjo** [comment]
I appreciate that it's frustrating to not be able to upload many videos, but there is really nothing I can do to help with that - Google have made the rules.

 There are already programs for uploading to Youtube that use http cookies etc - most of them are for Windows.  Just do a Google search and you will find them. Best of luck!
