### ISSUE TITLE
Get title, description and tags from a json file

### ISSUE THREAD

**Issue by umrug** [porjo/youtubeuploader#8]
Hi, thanks for your work.
A question: is there a way to serve title, description and tags to youtubeuploader from a json file?
Thanks,
Francesco

**Comment by porjo** [comment]
Hi, I've added a `-metaJSON` command line flag now. Pass it a file containing something like:

```json
{
  "title": "my test title",
  "description": "my test description",
  "tags": ["test tag1", "test tag2"],
  "privacyStatus": "public",
  "categoryId": "10"
}
```

**Comment by umrug** [comment]
Thanks Porjo.
Have a nice day
