### ISSUE TITLE
Large video stuck in incomplete state

### ISSUE THREAD

**Issue by dotneB** [porjo/youtubeuploader#85]
With a small video (6.11 MB, 24s m4v file) uploading with this tool works great.
But uploading a bigger file (5.12 GB, 1h 33m 05s m4v file) leaves the video in an incomplete state

Here's the commands I used and their output
```
❯ .\youtubeuploader.exe -filename 'G:\_Videos\Stream Clips\SmallTest.m4v' -title "Test title" -description "" -privacy "unlisted"
Uploading file 'G:\_Videos\Stream Clips\SmallTest.m4v'
Progress:    17.36 Mbps, 6413042 / 6412613 (100.007%) ETA       0s
Upload successful! Video ID: MOInXFZeLWc

❯ .\youtubeuploader.exe -filename 'G:\_Videos\Stream Clips\LargeTest.m4v' -title "Test larger video" -description "" -privacy "unlisted"
Uploading file 'G:\_Videos\Stream Clips\LargeTest.m4v'
Progress:    17.51 Mbps, 5501928752 / 5501928752 (100.000%) ETA       0s
Upload successful! Video ID: ffoiuDspQrw
```
Both files are reporte as Upload successful

But on the dasboard, the "Test larger video" get stuck it this state
![image](https://user-images.githubusercontent.com/55632/90450358-85ffeb00-e0b7-11ea-8ef9-655481d0e339.png)

Uploading LargeTest.m4v via youtube's dashboard works, so it doesn't seem to be the video itself.

**Comment by Jaom** [comment]
Is it still stuck? In my case it appeared as in yours (pretending to wait for the upload) but after some time it suddenly become available as a fully processed video.

**Comment by dotneB** [comment]
Oh, you are correct. After a _long_ while it does they get unstucked and becomes available. Thanks, closing the issue
