### ISSUE TITLE
Error adding video to playlist: googleapi: Error 404: Video not found., videoNotFound

### ISSUE THREAD

**Issue by danguyf** [porjo/youtubeuploader#88]
I started getting this error, "Error adding video to playlist: googleapi: Error 404: Video not found., videoNotFound", over the weekend.  Despite the error, the videos are added to the playlist.

I am using the metaJSON argument and passing a single value array to playlistTitles.  My code for creating the JSON and calling youtubeuploader has not changed.

Has anyone else experienced this?

**Comment by danguyf** [comment]
In further testing, it is happening inconsistently but I haven't been able to determine a common factor to the failures (or successes).

**Comment by qome** [comment]
This is not an innocent bug. It breaks successful upload detection in scripts.

**Comment by porjo** [comment]
Closing for now, unless anyone is still seeing this issue?
