### ISSUE TITLE
Multi-line description

### ISSUE THREAD

**Issue by NeoTheThird** [porjo/youtubeuploader#9]
Hey, this may be a stupid question, but is it possible to create a multi-line video description? If so, how do you do it?
Thanks in advance

**Comment by porjo** [comment]
If you use the new -metaJSON flag you can embed newlines into that by using `\n` e.g.

```json
{
"description": "line1\nline2"
}
```
Should produce:
```
line1
line2
```

v1.6 had a nasty bug which I've just fixed, so make sure you get the latest version v1.6.1

**Comment by NeoTheThird** [comment]
Thanks!
