### ISSUE TITLE
Resumable Uploads

### ISSUE THREAD

**Issue by SlavkoPavlovic** [porjo/youtubeuploader#90]
Is there a way to resume uploads if they're interrupted due to an unstable internet connection or user intervention? If not, it should be added from this link: https://developers.google.com/youtube/v3/guides/using_resumable_upload_protocol

**Comment by porjo** [comment]
Yes, I believe this is already supported - see this code that handles the upload:

https://github.com/googleapis/google-api-go-client/blob/master/youtube/v3/youtube-gen.go#L23285

**Comment by SlavkoPavlovic** [comment]
How do I use it ? Sometimes my upload gets interrupted. And when I start the upload again after a few minutes, it starts from zero.

**Comment by porjo** [comment]
The 'Resumable Uploads' document you linked to is what google-api-go-client is already doing AFAIK. It will handle transient server errors, and short network interruptions within the same upload session. It's not intended for resuming an upload over different sessions. I'm not sure that Youtube supports that unfortunately, but happy to be proven wrong.

**Comment by porjo** [comment]
I guess you could rewrite the HTTP client to save out the session URL to be used later if the upload were interrupted. I think it would be better to stick with the client that Google provides and maintains

**Comment by Tsaukpaetra** [comment]
Yeah I just encountered this issue, the uploader died because a request timed out, and did not attempt to resume upload at all.

```
2021/06/22 13:09:23 Error making YouTube API call: Post "https://www.googleapis.com/upload/youtube/v3/videos?alt=json&notifySubscribers=true&part=snippet&part=status&part=recordingDetails&prettyPrint=false&uploadType=resumable&upload_id=[REDACTED]": read tcp [2600:8800:1580:11e:225:REDACTED]:37138->[2607:f8b0:4007:80f::200a]:443: read: connection timed out
```

So clearly the google client is expecting the developer to react to failures and doesn't just retry for you...

**Comment by oliverw** [comment]
Why was this closed?

**Comment by porjo** [comment]
@oliverw  this ticket was closed because Google API client (which youtubeuploader uses) already handles resuming uploads within the same session (i.e. a single use of the utility). I've tested this by inserting a firewall rule on my localhost to REJECT outbound packets for a short period and observed that the transfer rate reduces to zero then picks up again automatically once the firewall rule is removed. No error is produced and the upload completes successfully.

Handling resuming of uploads across different sessions is not supported by Youtube API (as far as I know). 

Regarding network timeout reported by @Tsaukpaetra , I would need to see more context on the specific issue, but my guess is that the client reached a retry deadline and gave up (it's not going to retry forever).

**Comment by Tsaukpaetra** [comment]
Yeah IDK, apparently since I'm not able to get the right kind of App thing in the Google Code whatever, any video I ended up uploading ended up being flagged and perma-privated as bot spam so I ended up giving up. 🤷‍♂️

**Comment by oliverw** [comment]
> @oliverw this ticket was closed because Google API client (which youtubeuploader uses) already handles resuming uploads within the same session (i.e. a single use of the utility). I've tested this by inserting a firewall rule on my localhost to REJECT outbound packets for a short period and observed that the transfer rate reduces to zero then picks up again automatically once the firewall rule is removed. No error is produced and the upload completes successfully.
> 
> Handling resuming of uploads across different sessions is not supported by Youtube API (as far as I know).
> 
> Regarding network timeout reported by @Tsaukpaetra , I would need to see more context on the specific issue, but my guess is that the client reached a retry deadline and gave up (it's not going to retry forever).

Thansk for the explanation.
