### ISSUE TITLE
flag provided but not defined: -publish-at in youtubeuploader_mac_amd64

### ISSUE THREAD

**Issue by polatolu** [porjo/youtubeuploader#92]
I'm using the latest version of `youtubeuploader_mac_amd64` (Youtubeuploader version: 20.05-1-g125a7f6) and trying to upload a video with a scheduled date attached to it. 

However, I'm getting the below error, the CLI lists the available commands and it's really not in there. Does this parameter not available in mac version?

`flag provided but not defined: -publish-at`

**Comment by porjo** [comment]
@polatolu you specify that option via JSON file rather than command line parameter (not all options are available as command line parameters) - see https://github.com/porjo/youtubeuploader#metadata
