### ISSUE TITLE
Instructions missing

### ISSUE THREAD

**Issue by pbreah** [porjo/youtubeuploader#93]
First of all great YouTube uploader! one of the best! excellent work.

While trying to use it I noticed that when you don't have the request.token file I tried to load it from a remote site, I get this message on the console:

"Visit the URL below to get a code.  This program will pause until the site is visted"

But where is the URL? the URL is not below. There is also a typo: "visted" instead of "visited". May be a simple fix, but wanted to report this.

Thanks,

**Comment by porjo** [comment]
Thanks for the report. That was indeed a bug. I've fixed that in [latest release](https://github.com/porjo/youtubeuploader/releases/tag/21.02).
