### ISSUE TITLE
 Error making YouTube API call quotaExceeded

### ISSUE THREAD

**Issue by samelie** [porjo/youtubeuploader#94]
`Error making YouTube API call: googleapi: Error 403: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>., quotaExceeded`

- I've tried on multiple accounts

- All youtube APIs are enabled

If I delete `request.token` I go through the auth via the browser. I have not configured the 'OAuth consent screen'

Any ideas out there?

**Comment by samelie** [comment]
The issue was I was going to my global app's credentials to make the OAuth.

What fixed the issue was staying within APIs + Auth (Youtube Data API) and making the OAuth from there. 

This is a very ergonmic client, thank you!

**Comment by user4302** [comment]
could you possible elaborate on this?
im not sure what these mean
"global app's credentials"
"taying within APIs + Auth (Youtube Data API)"
