### ISSUE TITLE
Question: does the uploader continuously update with new refresh token?

### ISSUE THREAD

**Issue by pbreah** [porjo/youtubeuploader#96]
I'm having issues with the authentication part of the uploader. To give you a context of the setup: the uploader is part of a queue code that gets executed to upload videos as they get added.

The problem I am seeing is that after a some days of working flawlessly the token expires and the code stops working.

I am not proficient enough in go to send a pull request, but if the code is not updating the refresh token on the cache file, this problem would continue endlessly getting the error: "Token has been expired or revoked" after some days.

It would be nice for the uploader to keep updating the token cache file (request.token), with new refresh tokens it gets - so this part is maintenance free (having to manually authenticate repeatedly).

**Comment by porjo** [comment]
I've never had a problem with token expiring. Google doco says this however https://developers.google.com/identity/protocols/oauth2

```
A Google Cloud Platform project with an OAuth consent screen configured for an 
external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.
```

**Comment by pbreah** [comment]
Yes, that is the specific case I am using because there is no need to make the project public - just a single internal user. No user will interact with it (other than an Internal script). Probably adding an argument like -internal so it covers this use case of updating the token. Or what do you suggest?

**Comment by porjo** [comment]
As far as I know there is no way around it other than making your project public.

**Comment by majal** [comment]
> As far as I know there is no way around it other than making your project public.

Do we need to verify the app, or is making it public yet unverified enough to get token refresh?
